### ISSUE TITLE
Non-GCE job is calling "kubernetes_e2e.py/add_gce_ssh"

### ISSUE THREAD

**Issue by gyuho** [kubernetes/test-infra#10051]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-stable-aws-eks-1-10-prod/181 

https://github.com/kubernetes/test-infra/blob/0427f40f413cf9e05abe21b9662e44b476a0eacf/config/jobs/kubernetes/sig-aws/eks/k8s-aws-eks-1.10.yaml#L91-L112

does not require GCE SSH but test script tries to set `JENKINS_GCE_SSH_PRIVATE_KEY_FILE` from `~/.ssh/google_compute_engine`, as fails below

```
I1106 19:30:46.316] Call:  /workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py --check-leaked-resources --check-version-skew=false --deployment=eks --provider=eks --extract=ci/k8s-stable1 --ginkgo-parallel=30 '--test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8' --timeout=180m
W1106 19:30:46.364] Traceback (most recent call last):
W1106 19:30:46.364]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 758, in <module>
W1106 19:30:46.364]     main(parse_args())
W1106 19:30:46.365]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 590, in main
W1106 19:30:46.365]     mode.add_gce_ssh(args.gce_ssh, args.gce_pub)
W1106 19:30:46.365]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 234, in add_gce_ssh
W1106 19:30:46.365]     shutil.copy(priv, gce_ssh)
W1106 19:30:46.365]   File "/usr/lib/python2.7/shutil.py", line 119, in copy
W1106 19:30:46.365]     copyfile(src, dst)
W1106 19:30:46.365]   File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
W1106 19:30:46.365]     with open(src, 'rb') as fsrc:
W1106 19:30:46.366] IOError: [Errno 2] No such file or directory: '/root/.ssh/google_compute_engine'
E1106 19:30:46.372] Command failed
```

I checked the code and it is called from

https://github.com/kubernetes/test-infra/blob/0427f40f413cf9e05abe21b9662e44b476a0eacf/scenarios/kubernetes_e2e.py#L589-L590

But we are not passing `--gce-ssh` to `kubernetes_e2e.py`.

Does anybody know why this keeps failings? Did I write the test config wrong?

Thanks!

**Comment by gyuho** [comment]
There used to be `elif args.gce_ssh and args.provider != 'local':`

https://github.com/kubernetes/test-infra/pull/9915/files

Should we set `elif args.gce_ssh and args.provider != 'eks':`?
