### ISSUE TITLE
periobolos seg fault on dry run

### ISSUE THREAD

**Issue by jlewi** [kubernetes/test-infra#10186]
**What happened**:

I ran the periobolos command in dry run mode

```
periobolos --fix-org-members=true --config-path=/home/jlewi/git_kubeflow-internal-acls/github-orgs/kubeflow/org.yaml --github-token-path=/home/jlewi/github-kubeflow-org-admin-token --required-admins=jlewi,abhi-g,google-admin,googlebot,richardsliu,vicaire
```

This resulted in the seg fault

```
{"component":"peribolos","level":"info","msg":"Configuring org: name kubeflow","time":"2018-11-19T22:14:33-08:00"}
{"component":"peribolos","level":"info","msg":"Skipping org metadata configuration","time":"2018-11-19T22:14:33-08:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98d947]

goroutine 1 [running]:
k8s.io/test-infra/prow/github.(*Client).log(0x0, 0xc58b3f, 0x12, 0xc4200d3560, 0x1, 0x1)
	/home/jlewi/go/src/k8s.io/test-infra/prow/github/client.go:255 +0x37
k8s.io/test-infra/prow/github.(*Client).ListOrgInvitations(0x0, 0xc42024e550, 0x8, 0x509e7d, 0xc4200d3628, 0xc66b3c, 0x23, 0x0)
	/home/jlewi/go/src/k8s.io/test-infra/prow/github/client.go:556 +0xca
main.orgInvitations(0x7ffc8435909f, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3fd0000000000000, 0x5, 0x1, ...)
	/home/jlewi/go/src/k8s.io/test-infra/prow/cmd/peribolos/main.go:677 +0x81
main.configureOrg(0x7ffc8435909f, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3fd0000000000000, 0x5, 0x1, ...)
	/home/jlewi/go/src/k8s.io/test-infra/prow/cmd/peribolos/main.go:698 +0x124
main.main()
	/home/jlewi/go/src/k8s.io/test-infra/prow/cmd/peribolos/main.go:164 +0x5a2

Process finished with exit code 2

```
**What you expected to happen**:

Print out changes.

**How to reproduce it (as minimally and precisely as possible)**:

Run perobolos as above config is in kubeflow/internal-acls#20

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/kind bug

**Comment by jlewi** [comment]
Looks like this is fixed on master and I was using an old version.
