### ISSUE TITLE
Gubernator unable to retrieve recent run of job across PRs

### ISSUE THREAD

**Issue by yastij** [kubernetes/test-infra#10603]
Gubernator fails to retrieve pull-kubernetes-e2e-gke recent runs across PRs with the following: https://gubernator.k8s.io/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gke

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~k8s-gubernator/v20181206-526a12079.414498864628379355/view_base.py", line 85, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~k8s-gubernator/v20181206-526a12079.414498864628379355/view_build.py", line 394, in get
    builds, refs = build_list(job_dir, before)
  File "/base/data/home/apps/s~k8s-gubernator/v20181206-526a12079.414498864628379355/view_base.py", line 132, in wrapped
    data = func(*args)
  File "/base/data/home/apps/s~k8s-gubernator/v20181206-526a12079.414498864628379355/view_build.py", line 383, in build_list
    started, finished = normalize_metadata(started_future, finished_future)
  File "/base/data/home/apps/s~k8s-gubernator/v20181206-526a12079.414498864628379355/view_build.py", line 125, in normalize_metadata
    started = started_future.get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~k8s-gubernator/v20181206-526a12079.414498864628379355/gcs_async.py", line 45, in get
    result = yield context.urlfetch(url, headers=headers)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 1305, in urlfetch
    result = yield rpc
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 513, in _on_rpc_completion
    result = rpc.get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 615, in get_result
    return self.__get_result_hook(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7e468a4e2dbc991a/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 456, in _get_fetch_result
    raise DownloadError("Unable to fetch URL: " + url + error_detail)
DownloadError: Unable to fetch URL: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/72243/pull-kubernetes-e2e-gke/3774/started.json
```

**Comment by Katharine** [comment]
Oh, sorry, I think I misinterpreted the report - do you mean that the linked list itself wouldn't render? That seems very likely to be a `started.json` race of some sort.

I'm tempted to say wontfix, since Gubernator is in maintenance mode and headed to deprecation (also see #10375). The Deck replacement is https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gke

**Comment by Katharine** [comment]
/close

Gubernator is deprecated, not going to fix this.
