### ISSUE TITLE
kubetest does not dump logs when timing out

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#10865]
The nodes.yaml shows 4 nodes, but the there no logs from any of them in http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-min-node-permissions/495/artifacts/. Also bootstrap-e2e-master is empty expect for the serial log

```
W0121 20:21:19.499] 2019/01/21 20:21:19 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0121 20:21:19.500] 2019/01/21 20:21:19 main.go:315: Something went wrong: encountered 5 errors: [error during ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true (interrupted): signal: aborted (core dumped) error during ./cluster/log-dump/log-dump.sh /workspace/_artifacts (terminated): signal: killed Failed to list resources (skipped ./cluster/gce/list-resources.sh (kubetest is terminated)):
W0121 20:21:19.501]  skipped ./hack/e2e-internal/e2e-down.sh (kubetest is terminated) Failed to list resources (skipped ./cluster/gce/list-resources.sh (kubetest is terminated)):
W0121 20:21:19.501] ]
W0121 20:21:19.520] Traceback (most recent call last):
W0121 20:21:19.520]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 758, in <module>
W0121 20:21:19.521]     main(parse_args())
W0121 20:21:19.521]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 609, in main
W0121 20:21:19.521]     mode.start(runner_args)
W0121 20:21:19.521]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
W0121 20:21:19.522]     check_env(env, self.command, *args)
W0121 20:21:19.522]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0121 20:21:19.522]     subprocess.check_call(cmd, env=env)
W0121 20:21:19.522]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0121 20:21:19.522]     raise CalledProcessError(retcode, cmd)
W0121 20:21:19.523] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-node-image=gci', '--gcp-project=k8s-min-node-permissions', '--gcp-zone=us-central1-f', '--test_args=--ginkgo.skip=\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=500m')' returned non-zero exit status 1
E0121 20:21:19.561] Command failed
I0121 20:21:19.561] process 262 exited with code 1 after 515.5m
E0121 20:21:19.562] FAIL: ci-kubernetes-e2e-gce-min-node-permissions
```

from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-min-node-permissions/495/build-log.txt

**Comment by neolit123** [comment]
> 515.5m

a test running for 8.5 hours. :grimacing:

**Comment by krzyzacy** [comment]
kubetest leaves 15min for log-dumping after build timeout and the log dumping step itself timed out in 15min... I suspect the artifacts are GIANT for some reason?

(see 
```
W0121 20:20:49.498] 2019/01/21 20:20:49 process.go:193: Failed to terminate ./cluster/log-dump/log-dump.sh /workspace/_artifacts (terminated 15m after interrupt): os: process already finished
W0121 20:20:49.498] 2019/01/21 20:20:49 process.go:385: Failed to get the group process from 8810: no such process
W0121 20:20:49.499] 2019/01/21 20:20:49 process.go:193: Failed to terminate ./cluster/log-dump/log-dump.sh /workspace/_artifacts (terminated 15m after interrupt): os: process already finished
```
)
