### ISSUE TITLE
Deck Plugins Page Blank if Label Plugin Used Without Config

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11513]
**What happened**:
If I don't add any configuration to `plugins.yaml` for the `label` plugin and enable that plugin for a repo, I get a panic in hook logs like so:
```
[hook-66f5d6d4cc-svf2f] 2019/02/26 03:42:03 http: panic serving 192.168.179.144:59110: runtime error: invalid memory address or nil pointer dereference 
[hook-66f5d6d4cc-svf2f] goroutine 81 [running]: 
[hook-66f5d6d4cc-svf2f] net/http.(*conn).serve.func1(0xc0004c0000) 
[hook-66f5d6d4cc-svf2f]         GOROOT/src/net/http/server.go:1746 +0xd0 
[hook-66f5d6d4cc-svf2f] panic(0x13974e0, 0x22c3cd0) 
[hook-66f5d6d4cc-svf2f]         GOROOT/src/runtime/panic.go:513 +0x1b9 
[hook-66f5d6d4cc-svf2f] k8s.io/test-infra/prow/plugins/label.helpProvider(0xc0002098c0, 0x0, 0x0, 0x0, 0xc0003267a0, 0x0, 0x0) 
[hook-66f5d6d4cc-svf2f]         prow/plugins/label/label.go:47 +0x6e 
[hook-66f5d6d4cc-svf2f] k8s.io/test-infra/prow/pluginhelp/hook.(*HelpAgent).generateNormalPluginHelp(0xc00031d720, 0xc0002098c0, 0xc0002ab980, 0xc0002aba70, 0x40b7df, 0x7f027b040b00, 0xc0003be233) 
[hook-66f5d6d4cc-svf2f]         prow/pluginhelp/hook/hook.go:86 +0x187 
[hook-66f5d6d4cc-svf2f] k8s.io/test-infra/prow/pluginhelp/hook.(*HelpAgent).GeneratePluginHelp(0xc00031d720, 0x22fcc10) 
[hook-66f5d6d4cc-svf2f]         prow/pluginhelp/hook/hook.go:151 +0xbc 
[hook-66f5d6d4cc-svf2f] k8s.io/test-infra/prow/pluginhelp/hook.(*HelpAgent).ServeHTTP(0xc00031d720, 0x1710540, 0xc0003ee000, 0xc0004f0100) 
[hook-66f5d6d4cc-svf2f]         prow/pluginhelp/hook/hook.go:369 +0x212 
[hook-66f5d6d4cc-svf2f] net/http.(*ServeMux).ServeHTTP(0x22dd6a0, 0x1710540, 0xc0003ee000, 0xc0004f0100) 
[hook-66f5d6d4cc-svf2f]         GOROOT/src/net/http/server.go:2361 +0x127 
[hook-66f5d6d4cc-svf2f] net/http.serverHandler.ServeHTTP(0xc0000ab6c0, 0x1710540, 0xc0003ee000, 0xc0004f0100) 
[hook-66f5d6d4cc-svf2f]         GOROOT/src/net/http/server.go:2741 +0xab 
[hook-66f5d6d4cc-svf2f] net/http.(*conn).serve(0xc0004c0000, 0x1713600, 0xc00059a240) 
[hook-66f5d6d4cc-svf2f]         GOROOT/src/net/http/server.go:1847 +0x646 
[hook-66f5d6d4cc-svf2f] created by net/http.(*Server).Serve 
[hook-66f5d6d4cc-svf2f]         GOROOT/src/net/http/server.go:2851 +0x2f5 
```
**What you expected to happen**:
I expected the plugins page to load correctly and labels plugin to work correctly, but not really do anything.

**How to reproduce it (as minimally and precisely as possible)**:
Enable label plugin on a repo in `plugins.yaml`, don't add any config for label plugins, load plugins page for that repo in deck.

**Please provide links to example occurrences, if any**:
N/A

**Anything else we need to know?**:

**Comment by stevekuznetsov** [comment]
This should be fixed with #11490 
/close
