### ISSUE TITLE
bazel test //... -- -//vendor/... has external dependencies

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#11763]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-test-infra-autoupdate-patch/2

```console
INFO: From Testing //kettle:stream_test:
==================== Test output for //kettle:stream_test:
Traceback (most recent call last):
File "/home/prow/go/src/github.com/kubernetes/test-infra/kettle/stream.py", line 32, in <module>
from google.cloud import bigquery
ImportError: No module named google.cloud
WARNING: unable to load google cloud (test environment?)
Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/sandbox/processwrapper-sandbox/1776/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/kettle/stream_test.runfiles/io_k8s_test_infra/kettle/stream_test.py", line 21, in <module>
import stream
File "/home/prow/go/src/github.com/kubernetes/test-infra/kettle/stream.py", line 40, in <module>
import make_db
File "/home/prow/go/src/github.com/kubernetes/test-infra/kettle/make_db.py", line 33, in <module>
import yaml
ImportError: No module named yaml
================================================================================
```

**Comment by fejta** [comment]
My goal here is I want to be able to take a clean VM, install git and bazel, clone test infra and `bazel test //...` everything

**Comment by krzyzacy** [comment]
filter out all pytest? /shrug

**Comment by stevekuznetsov** [comment]
esp if we deprecate gubernator

**Comment by fejta** [comment]
OR we could, you know, write encapsulated tests rather than expecting the user to figure out how to fetch ten billion dependencies for different languages.

kettle isn't going away any time soon

**Comment by krzyzacy** [comment]
(rewrite kettle in go!)
