### ISSUE TITLE
upload_e2e.py TokenRevokeError

### ISSUE THREAD

**Issue by OlegLoewen** [kubernetes/test-infra#11847]
**What happened**:
Invoking the upload_e2e.py is causing the following error, which hasn't occured in the past:
```
Run: ['gcloud', 'auth', 'revoke']
ERROR: gcloud crashed (TokenRevokeError): invalid_request

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./test-infra/testgrid/conformance/upload_e2e.py", line 290, in <lambda>
    atexit.register(lambda: revoke_current_account(args.dry_run))
  File "./test-infra/testgrid/conformance/upload_e2e.py", line 224, in revoke_current_account
    return subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['gcloud', 'auth', 'revoke']' returned non-zero exit status 1
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./test-infra/testgrid/conformance/upload_e2e.py", line 290, in <lambda>
    atexit.register(lambda: revoke_current_account(args.dry_run))
  File "./test-infra/testgrid/conformance/upload_e2e.py", line 224, in revoke_current_account
    return subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcloud', 'auth', 'revoke']' returned non-zero exit status 1
```

**What you expected to happen**:
In the past the upload was working fine. Looks like a regression issue.

**How to reproduce it (as minimally and precisely as possible)**:
Using google-cloud-sdk-226.0.0-linux-x86_64.tar.gz
Upload anything with `python2 ./test-infra/testgrid/conformance/upload_e2e.py --junit="$log_dir/junit_01.xml" --log="$e2e_log" --bucket=gs://yourbucket  --key-file=$google_bucket_secrets_file`

**Comment by BenTheElder** [comment]
Please CC me on upload_e2e.py issues, I do not monitor this repo closely but I do flag mentions in my inbox. I don't think anyone else is likely to help with this unfortunately.

**Comment by BenTheElder** [comment]
It's possible 226 is too old, can you try updating the gcloud SDK?

**Comment by BenTheElder** [comment]
This script has not changed in 10 months FWIW https://github.com/kubernetes/test-infra/blob/master/testgrid/conformance/upload_e2e.py

**Comment by BenTheElder** [comment]
Please re-open or file a new issue if you have further details.
