### ISSUE TITLE
Make bootstrap_test pass remotely

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12195]
```
ERROR: test_batch (__main__.IntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/b/f/w/bazel-out/k8-fastbuild/bin/jenkins/bootstrap_test.runfiles/io_k8s_test_infra/jenkins/bootstrap_test.py", line 1430, in test_batch
root=self.root_workspace)
File "/b/f/w/bazel-out/k8-fastbuild/bin/jenkins/bootstrap_test.runfiles/io_k8s_test_infra/jenkins/bootstrap_test.py", line 1101, in test_bootstrap
return bootstrap.bootstrap(FakeArgs(**kw))
File "/b/f/w/bazel-out/k8-fastbuild/bin/jenkins/bootstrap_test.runfiles/io_k8s_test_infra/jenkins/bootstrap.py", line 1102, in bootstrap
call(job_script(job, args.scenario, args.extra_job_args))
File "/b/f/w/bazel-out/k8-fastbuild/bin/jenkins/bootstrap_test.runfiles/io_k8s_test_infra/jenkins/bootstrap.py", line 1054, in <lambda>
call = lambda *a, **kw: _call(end, *a, **kw)
File "/b/f/w/bazel-out/k8-fastbuild/bin/jenkins/bootstrap_test.runfiles/io_k8s_test_infra/jenkins/bootstrap.py", line 110, in _call
env=env,
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-test-infra-bazel-rbe/1117126460855816201

**Comment by fejta** [comment]
Appears we may need to use an image that has git
