### ISSUE TITLE
Some jobs are using an incompatible bazel version (<0.26.0).

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#12981]
Affected jobs:
- https://prow.k8s.io/?job=ci-test-infra-autobump-prow
- https://prow.k8s.io/?job=maintenance-ci-testgrid-config-upload

Example error:
```
ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': Traceback (most recent call last):
File "/bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 279
_check_min_bazel_version("yarn_install", repository_ctx)
File "/bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 150, in _check_min_bazel_version
check_bazel_version(message = ("\n A minimum ...)), ...")
File "/bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl", line 53, in check_bazel_version
fail("\nCurrent Bazel version is {}, ...))
Current Bazel version is 0.23.2, expected at least 0.26.0
A minimum Bazel version of 0.26.0 is required for the yarn_install @npm repository rule.
By default, yarn_install and npm_install in build_bazel_rules_nodejs >= 0.30.0
depends on the managed directory feature added in Bazel 0.26.0. See
https://github.com/bazelbuild/rules_nodejs/wiki#migrating-to-rules_nodejs-030.
You can opt out of this feature by setting `symlink_node_modules = False`
on all of your yarn_install & npm_install rules.
```

Likely caused by this PR: https://github.com/kubernetes/test-infra/pull/12855

**Comment by cjwagner** [comment]
/assign @cjwagner @fejta 
/cc @Katharine @stevekuznetsov 
Updating/adding image variants for bazel 0.26.0: https://github.com/kubernetes/test-infra/pull/12855

**Comment by cjwagner** [comment]
I retriggered the autobump job.
If it runs successfully we will have fixed one of the broken jobs and when we merge the PR it creates that should fix the testgrid config upload job too.
