### ISSUE TITLE
build errors on bazel 0.27.0

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13140]
```
ERROR: /usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/c229eee16670a3bb15d65c08362dcf5d/external/io_k8s_repo_infra/defs/run_in_workspace.bzl:48:16: Traceback (most recent call last):
	File "/usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/c229eee16670a3bb15d65c08362dcf5d/external/io_k8s_repo_infra/defs/run_in_workspace.bzl", line 46
		rule(attrs = {"cmd": attr.label(manda...)}, <2 more arguments>)
	File "/usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/c229eee16670a3bb15d65c08362dcf5d/external/io_k8s_repo_infra/defs/run_in_workspace.bzl", line 48, in rule
		attr.label(mandatory = True, allow_files = Tr..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
```

**Comment by fejta** [comment]
More work done here: https://github.com/kubernetes/test-infra/pull/13204#issuecomment-506585743
