### ISSUE TITLE
checkconfig: unknown fields check panics

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#13154]
```
panic: reflect: call of reflect.Value.Index on ptr Value
goroutine 1 [running]:
reflect.Value.Index(0x134eb40, 0xc0015b92f0, 0x96, 0x0, 0x2, 0xc0035e32e0, 0x1f)
	GOROOT/src/reflect/value.go:942 +0x1d0
main.checkUnknownFields(0xc0035e32c0, 0x1c, 0x137aec0, 0xc00161d140, 0x134eb40, 0xc0015b92f0, 0x96, 0x96, 0x0, 0x0)
	prow/cmd/checkconfig/main.go:372 +0x229
main.checkUnknownFields(0xc0035e3280, 0x13, 0x1401ba0, 0xc000eaf290, 0x14d9f20, 0xc0015b92e0, 0x99, 0x99, 0xc0020b6e38, 0x12bf915)
	prow/cmd/checkconfig/main.go:365 +0x72a
main.checkUnknownFields(0xc0035e3260, 0x11, 0x1401ba0, 0xc000eaf110, 0x1401fc0, 0xc002430fb0, 0x195, 0x195, 0xc0020b6fe0, 0x12bf915)
	prow/cmd/checkconfig/main.go:365 +0x72a
main.checkUnknownFields(0xc00184a920, 0x9, 0x1401ba0, 0xc000eaef90, 0x14863c0, 0xc002430fb0, 0x199, 0x199, 0x0, 0x0)
	prow/cmd/checkconfig/main.go:365 +0x72a
main.checkUnknownFields(0x0, 0x0, 0x1401ba0, 0xc001005410, 0x14d6860, 0xc002430f00, 0x16, 0x0, 0x0, 0x0)
	prow/cmd/checkconfig/main.go:365 +0x72a
main.validateUnknownFields(0x14d6860, 0xc002430f00, 0xc003452000, 0x620e, 0x640e, 0x7ffe44b0fa08, 0x25, 0x0, 0x0)
	prow/cmd/checkconfig/main.go:345 +0x23f
main.main()
	prow/cmd/checkconfig/main.go:225 +0x980
```

/area prow/checkconfig

**Comment by stevekuznetsov** [comment]
Looks like this is a failure to consider that a `*[]string{}` is technically `[]interface{}`?

**Comment by cjwagner** [comment]
This is fixed.
/close
