### ISSUE TITLE
metrics-bigquery job is failing

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14106]
**What happened**:
Received a TestGrid alert that the job has failed twice. It appears to be a problem with the `bq query` command:
```
# example
W0827 23:55:12.540] Traceback (most recent call last):
W0827 23:55:12.540]   File "test-infra/metrics/bigquery.py", line 250, in main
W0827 23:55:12.540]     queryer.run_metric(config)
W0827 23:55:12.540]   File "test-infra/metrics/bigquery.py", line 128, in run_metric
W0827 23:55:12.540]     self.do_query(config['query'], raw)
W0827 23:55:12.540]   File "test-infra/metrics/bigquery.py", line 89, in do_query
W0827 23:55:12.540]     check(cmd, stdout=out_file)
W0827 23:55:12.540]   File "test-infra/metrics/bigquery.py", line 50, in check
W0827 23:55:12.540]     subprocess.check_call(cmd, **kwargs)
W0827 23:55:12.540]   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
W0827 23:55:12.541]     raise CalledProcessError(retcode, cmd)
W0827 23:55:12.541] subprocess.CalledProcessError: Command '['bq', 'query', '--format=prettyjson', '--project_id=k8s-gubernator', '-n1000000', "#standardSQL\nselect\n  unix_seconds(day) day,\n  invocations,\n  passes,\n  if (invocations > 0, passes / invocations, 1) rate\nfrom (\nSELECT\n  timestamp_trunc(started, day) day,\n  COUNT(started) invocations,\n  countif(result = 'SUCCESS') passes\nFROM\n  `k8s-gubernator.build.all`\nwhere\n  started >= TIMESTAMP_SECONDS(1566604800)\n  and started < timestamp_trunc(current_timestamp(), day)\ngroup by day\norder by day\n)\nwhere day is not null\norder by day\n"]' returned non-zero exit status 1.
```
```
I0827 23:56:35.667] Failed 10 configs: test-infra/metrics/configs/weekly-consistency-config.yaml, test-infra/metrics/configs/build-stats.yaml, test-infra/metrics/configs/failures-config.yaml, test-infra/metrics/configs/pr-consistency-config.yaml, test-infra/metrics/configs/job-flakes-config.yaml, test-infra/metrics/configs/flakes-daily-config.yaml, test-infra/metrics/configs/istio-flakes.yaml, test-infra/metrics/configs/presubmit-health.yaml, test-infra/metrics/configs/job-health.yaml, test-infra/metrics/configs/flakes-config.yaml
```

**Please provide links to example occurrences, if any**:
https://k8s-testgrid.appspot.com/sig-testing-misc#metrics-bigquery
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/metrics-bigquery/1166499151081377792

/assign @fejta @michelle192837 
cc @clarketm

**Comment by clarketm** [comment]
This should be resolvable by bumping the SDK in [image](https://github.com/kubernetes/test-infra/blob/master/images/bigquery/Dockerfile). https://issuetracker.google.com/issues/117948931

**Comment by BenTheElder** [comment]
the above issue was marked fixed, have we followed up on this?

**Comment by BenTheElder** [comment]
> W1003 00:27:46.525] /google-cloud-sdk/platform/bq/third_party/oauth2client_4_0/_helpers.py:256: UserWarning: Cannot access /workspace/.config/gcloud/legacy_credentials/triage@k8s-gubernator.iam.gserviceaccount.com/singlestore_bq.json: No such file or directory

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/metrics-bigquery/1179553029154672645/

**Comment by clarketm** [comment]
Looks good! 
https://testgrid.k8s.io/sig-testing-misc#metrics-bigquery

**Comment by BenTheElder** [comment]
two passes after _actually_ upgrading the image, I think we can close now https://github.com/kubernetes/test-infra/pull/14624
