### ISSUE TITLE
`bazel test //...` does not detect compile errors when run locally.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14429]
**What happened**:
I ran `bazel test //...` on my local machine to test some changes. It passed (besides pylint which apparently always fails locally for everyone), but when I pushed my changes the bazel presubmit failed due to legitimate compile errors that were not identified locally.

**What you expected to happen**:
`bazel test //...` should behave the same as the `pull-test-infra-bazel` job. At minimum I'd expect to be alerted of the same compile errors.

**Please provide links to example occurrences, if any**:
Here is a failed presubmit run on commit `688843f8cb02eaf12d7d5b1b95c27585300e15d8` https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/14415/pull-test-infra-bazel/1175154363140673537

Here is my terminal output running on the same commit (go module spam omitted). Notice that there is no entry for `config-bootstrapper` which is the component with the compile error. I also had the same problems with compiling `needs-rebase`.
<details>

```
INFO: Analyzed 200 targets (1 packages loaded, 4851 targets configured).
INFO: Found 200 test targets...
FAIL: //hack:verify-pylint (see /usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/testlogs/hack/verify-pylint/test.log)
INFO: From Testing //hack:verify-pylint:
==================== Test output for //hack:verify-pylint:
Linting python...
Traceback (most recent call last):
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/io_k8s_test_infra/hack/pylint_bin.py", line 55, in <module>
    pylint.run_pylint()
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__pylint_1_9_5/pylint/__init__.py", line 15, in run_pylint
    from pylint.lint import Run
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__pylint_1_9_5/pylint/lint.py", line 64, in <module>
    import astroid
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__astroid_1_6_6/astroid/__init__.py", line 57, in <module>
    from astroid.nodes import *
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__astroid_1_6_6/astroid/nodes.py", line 18, in <module>
    from astroid.node_classes import (
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__astroid_1_6_6/astroid/node_classes.py", line 25, in <module>
    from astroid import bases
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__astroid_1_6_6/astroid/bases.py", line 25, in <module>
    MANAGER = manager.AstroidManager()
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__astroid_1_6_6/astroid/util.py", line 24, in <lambda>
    lambda: importlib.import_module('.' + module_name, 'astroid'))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__astroid_1_6_6/astroid/manager.py", line 21, in <module>
    from astroid.interpreter._import import spec
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/sandbox/linux-sandbox/3981/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__astroid_1_6_6/astroid/interpreter/_import/spec.py", line 19, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
================================================================================
INFO: Elapsed time: 12.519s, Critical Path: 1.33s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//boskos:go_default_test                                        (cached) PASSED in 1.6s
//boskos/cleaner:go_default_test                                (cached) PASSED in 1.4s
//boskos/client:go_default_test                                 (cached) PASSED in 1.2s
//boskos/cmd/cli:go_default_test                                (cached) PASSED in 6.9s
//boskos/common:go_default_test                                 (cached) PASSED in 1.3s
//boskos/janitor:go_default_test                                (cached) PASSED in 1.8s
//boskos/mason:go_default_test                                  (cached) PASSED in 3.5s
//boskos/ranch:go_default_test                                  (cached) PASSED in 1.6s
//config/tests/jobs:go_default_test                             (cached) PASSED in 4.2s
//config/tests/testgrids:go_default_test                        (cached) PASSED in 5.0s
//experiment/add-hook:go_default_test                           (cached) PASSED in 1.4s
//experiment/autobumper/bumper:go_default_test                  (cached) PASSED in 1.3s
//experiment/ci-janitor:go_default_test                         (cached) PASSED in 1.6s
//experiment/config-forker:go_default_test                      (cached) PASSED in 1.5s
//experiment/coverage:go_default_test                           (cached) PASSED in 1.6s
//experiment/dummybenchmarks:go_default_test                    (cached) PASSED in 1.1s
//experiment/dummybenchmarks/subpkg:go_default_test             (cached) PASSED in 1.6s
//experiment/image-bumper/bumper:go_default_test                (cached) PASSED in 1.3s
//experiment/logviewer/gcsreader:go_default_test                (cached) PASSED in 1.3s
//experiment/resultstore:go_default_test                        (cached) PASSED in 1.6s
//experiment/tracer:go_default_test                             (cached) PASSED in 1.4s
//ghproxy/ghcache:go_default_test                               (cached) PASSED in 7.6s
//ghproxy/ghmetrics:go_default_test                             (cached) PASSED in 1.3s
//gopherage/cmd/html/static:utils_test                          (cached) PASSED in 1.2s
//gopherage/pkg/cov:go_default_test                             (cached) PASSED in 1.2s
//gopherage/pkg/cov/junit/calculation:go_default_test           (cached) PASSED in 1.2s
//greenhouse/diskcache:go_default_test                          (cached) PASSED in 1.2s
//hack:coalesce_test                                            (cached) PASSED in 0.2s
//hack:verify-bazel                                             (cached) PASSED in 4.2s
//hack:verify-codegen                                           (cached) PASSED in 57.3s
//hack:verify-config                                            (cached) PASSED in 0.9s
//hack:verify-deps                                              (cached) PASSED in 52.8s
//hack:verify-gofmt                                             (cached) PASSED in 2.9s
//hack:verify-gopherage                                         (cached) PASSED in 0.4s
//hack:verify-labels                                            (cached) PASSED in 1.6s
//hack:verify-protos                                            (cached) PASSED in 1.1s
//hack:verify-spelling                                          (cached) PASSED in 27.1s
//hack:verify-tslint                                            (cached) PASSED in 4.7s
//hack:verify_boilerplate                                       (cached) PASSED in 0.8s
//jenkins:bootstrap_test                                        (cached) PASSED in 9.1s
//kettle:make_db_test                                           (cached) PASSED in 4.7s
//kettle:make_json_test                                         (cached) PASSED in 0.4s
//kettle:model_test                                             (cached) PASSED in 0.2s
//kettle:stream_test                                            (cached) PASSED in 1.0s
//kubetest:go_default_test                                      (cached) PASSED in 1.7s
//kubetest/kubeadmdind:go_default_test                          (cached) PASSED in 1.2s
//kubetest/process:go_default_test                              (cached) PASSED in 3.3s
//kubetest/util:go_default_test                                 (cached) PASSED in 1.3s
//kubetest2/pkg/metadata:go_default_test                        (cached) PASSED in 1.1s
//label_sync:go_default_test                                    (cached) PASSED in 1.7s
//maintenance/aws-janitor/resources:go_default_test             (cached) PASSED in 1.3s
//maintenance/migratestatus/migrator:go_default_test            (cached) PASSED in 1.2s
//metrics:bigquery_test                                         (cached) PASSED in 1.1s
//pkg/benchmarkjunit:go_default_test                            (cached) PASSED in 13.0s
//pkg/gencred:go_default_test                                   (cached) PASSED in 5.4s
//pkg/genyaml:go_default_test                                   (cached) PASSED in 1.6s
//pkg/ghclient:go_default_test                                  (cached) PASSED in 1.3s
//prow/apis/prowjobs/v1:go_default_test                         (cached) PASSED in 1.4s
//prow/bugzilla:go_default_test                                 (cached) PASSED in 1.3s
//prow/clonerefs:go_default_test                                (cached) PASSED in 1.4s
//prow/cluster:go_default_test                                  (cached) PASSED in 1.2s
//prow/cmd/admission:go_default_test                            (cached) PASSED in 1.9s
//prow/cmd/branchprotector:go_default_test                      (cached) PASSED in 1.5s
//prow/cmd/build:go_default_test                                (cached) PASSED in 1.6s
//prow/cmd/checkconfig:go_default_test                          (cached) PASSED in 1.7s
//prow/cmd/crier:go_default_test                                (cached) PASSED in 1.4s
//prow/cmd/deck:go_default_test                                 (cached) PASSED in 1.5s
//prow/cmd/deck/static:prow_test                                (cached) PASSED in 0.4s
//prow/cmd/gerrit:go_default_test                               (cached) PASSED in 1.4s
//prow/cmd/hook:go_default_test                                 (cached) PASSED in 1.6s
//prow/cmd/horologium:go_default_test                           (cached) PASSED in 1.6s
//prow/cmd/jenkins-operator:go_default_test                     (cached) PASSED in 1.4s
//prow/cmd/mkbuild-cluster:go_default_test                      (cached) PASSED in 1.5s
//prow/cmd/mkpj:go_default_test                                 (cached) PASSED in 1.6s
//prow/cmd/mkpod:go_default_test                                (cached) PASSED in 1.5s
//prow/cmd/peribolos:go_default_test                            (cached) PASSED in 1.6s
//prow/cmd/phaino:go_default_test                               (cached) PASSED in 1.4s
//prow/cmd/pipeline:go_default_test                             (cached) PASSED in 1.5s
//prow/cmd/plank:go_default_test                                (cached) PASSED in 1.4s
//prow/cmd/sinker:go_default_test                               (cached) PASSED in 1.5s
//prow/cmd/tackle:go_default_test                               (cached) PASSED in 1.4s
//prow/cmd/tide:go_default_test                                 (cached) PASSED in 1.5s
//prow/cmd/tot:go_default_test                                  (cached) PASSED in 5.0s
//prow/commentpruner:go_default_test                            (cached) PASSED in 1.2s
//prow/config:go_default_test                                   (cached) PASSED in 7.6s
//prow/config/jobtests:go_default_test                          (cached) PASSED in 5.2s
//prow/config/org:go_default_test                               (cached) PASSED in 1.2s
//prow/config/secret:go_default_test                            (cached) PASSED in 1.3s
//prow/crier:go_default_test                                    (cached) PASSED in 2.0s
//prow/cron:go_default_test                                     (cached) PASSED in 1.5s
//prow/deck/jobs:go_default_test                                (cached) PASSED in 1.5s
//prow/entrypoint:go_default_test                               (cached) PASSED in 4.7s
//prow/external-plugins/cherrypicker:go_default_test            (cached) PASSED in 3.5s
//prow/external-plugins/needs-rebase/plugin:go_default_test     (cached) PASSED in 1.5s
//prow/flagutil:go_default_test                                 (cached) PASSED in 1.5s
//prow/gcsupload:go_default_test                                (cached) PASSED in 1.5s
//prow/genfiles:go_default_test                                 (cached) PASSED in 1.3s
//prow/gerrit/adapter:go_default_test                           (cached) PASSED in 1.4s
//prow/gerrit/client:go_default_test                            (cached) PASSED in 1.3s
//prow/gerrit/reporter:go_default_test                          (cached) PASSED in 1.6s
//prow/git:go_default_test                                      (cached) PASSED in 4.1s
//prow/gitattributes:go_default_test                            (cached) PASSED in 1.4s
//prow/github:go_default_test                                   (cached) PASSED in 2.1s
//prow/github/report:go_default_test                            (cached) PASSED in 1.5s
//prow/github/reporter:go_default_test                          (cached) PASSED in 1.5s
//prow/githuboauth:go_default_test                              (cached) PASSED in 1.5s
//prow/hook:go_default_test                                     (cached) PASSED in 1.4s
//prow/initupload:go_default_test                               (cached) PASSED in 1.5s
//prow/interrupts:go_default_test                               (cached) PASSED in 2.1s
//prow/jenkins:go_default_test                                  (cached) PASSED in 8.0s
//prow/kube:go_default_test                                     (cached) PASSED in 2.1s
//prow/pjutil:go_default_test                                   (cached) PASSED in 1.5s
//prow/plank:go_default_test                                    (cached) PASSED in 2.2s
//prow/pluginhelp/hook:go_default_test                          (cached) PASSED in 2.5s
//prow/plugins:go_default_test                                  (cached) PASSED in 1.5s
//prow/plugins/approve:go_default_test                          (cached) PASSED in 1.8s
//prow/plugins/approve/approvers:go_default_test                (cached) PASSED in 1.3s
//prow/plugins/assign:go_default_test                           (cached) PASSED in 1.4s
//prow/plugins/blockade:go_default_test                         (cached) PASSED in 1.5s
//prow/plugins/blunderbuss:go_default_test                      (cached) PASSED in 1.6s
//prow/plugins/branchcleaner:go_default_test                    (cached) PASSED in 1.5s
//prow/plugins/bugzilla:go_default_test                         (cached) PASSED in 1.5s
//prow/plugins/buildifier:go_default_test                       (cached) PASSED in 2.7s
//prow/plugins/cat:go_default_test                              (cached) PASSED in 1.4s
//prow/plugins/cherrypickunapproved:go_default_test             (cached) PASSED in 1.5s
//prow/plugins/cla:go_default_test                              (cached) PASSED in 1.4s
//prow/plugins/dco:go_default_test                              (cached) PASSED in 1.5s
//prow/plugins/docs-no-retest:go_default_test                   (cached) PASSED in 1.6s
//prow/plugins/dog:go_default_test                              (cached) PASSED in 1.4s
//prow/plugins/golint:go_default_test                           (cached) PASSED in 14.3s
//prow/plugins/golint/suggestion:go_default_test                (cached) PASSED in 1.3s
//prow/plugins/heart:go_default_test                            (cached) PASSED in 1.7s
//prow/plugins/help:go_default_test                             (cached) PASSED in 1.5s
//prow/plugins/hold:go_default_test                             (cached) PASSED in 1.3s
//prow/plugins/invalidcommitmsg:go_default_test                 (cached) PASSED in 1.7s
//prow/plugins/label:go_default_test                            (cached) PASSED in 1.8s
//prow/plugins/lgtm:go_default_test                             (cached) PASSED in 1.5s
//prow/plugins/lifecycle:go_default_test                        (cached) PASSED in 1.4s
//prow/plugins/mergecommitblocker:go_default_test               (cached) PASSED in 3.4s
//prow/plugins/milestone:go_default_test                        (cached) PASSED in 1.6s
//prow/plugins/milestoneapplier:go_default_test                 (cached) PASSED in 1.4s
//prow/plugins/milestonestatus:go_default_test                  (cached) PASSED in 1.7s
//prow/plugins/override:go_default_test                         (cached) PASSED in 1.7s
//prow/plugins/owners-label:go_default_test                     (cached) PASSED in 1.6s
//prow/plugins/pony:go_default_test                             (cached) PASSED in 1.6s
//prow/plugins/project:go_default_test                          (cached) PASSED in 2.0s
//prow/plugins/releasenote:go_default_test                      (cached) PASSED in 1.7s
//prow/plugins/require-matching-label:go_default_test           (cached) PASSED in 1.7s
//prow/plugins/requiresig:go_default_test                       (cached) PASSED in 1.6s
//prow/plugins/retitle:go_default_test                          (cached) PASSED in 1.5s
//prow/plugins/shrug:go_default_test                            (cached) PASSED in 1.7s
//prow/plugins/sigmention:go_default_test                       (cached) PASSED in 1.5s
//prow/plugins/size:go_default_test                             (cached) PASSED in 1.4s
//prow/plugins/skip:go_default_test                             (cached) PASSED in 1.4s
//prow/plugins/slackevents:go_default_test                      (cached) PASSED in 1.4s
//prow/plugins/stage:go_default_test                            (cached) PASSED in 1.5s
//prow/plugins/trigger:go_default_test                          (cached) PASSED in 1.5s
//prow/plugins/updateconfig:go_default_test                     (cached) PASSED in 1.4s
//prow/plugins/verify-owners:go_default_test                    (cached) PASSED in 28.8s
//prow/plugins/welcome:go_default_test                          (cached) PASSED in 1.6s
//prow/plugins/wip:go_default_test                              (cached) PASSED in 1.6s
//prow/plugins/yuks:go_default_test                             (cached) PASSED in 1.4s
//prow/pod-utils/clone:go_default_test                          (cached) PASSED in 1.7s
//prow/pod-utils/decorate:go_default_test                       (cached) PASSED in 1.7s
//prow/pod-utils/downwardapi:go_default_test                    (cached) PASSED in 1.3s
//prow/pod-utils/gcs:go_default_test                            (cached) PASSED in 1.3s
//prow/pod-utils/wrapper:go_default_test                        (cached) PASSED in 1.1s
//prow/prstatus:go_default_test                                 (cached) PASSED in 2.5s
//prow/pubsub/reporter:go_default_test                          (cached) PASSED in 1.6s
//prow/pubsub/subscriber:go_default_test                        (cached) PASSED in 1.8s
//prow/repoowners:go_default_test                               (cached) PASSED in 37.5s
//prow/sidecar:go_default_test                                  (cached) PASSED in 1.5s
//prow/simplifypath:go_default_test                             (cached) PASSED in 1.3s
//prow/slack/reporter:go_default_test                           (cached) PASSED in 1.5s
//prow/spyglass:go_default_test                                 (cached) PASSED in 1.7s
//prow/spyglass/lenses:go_default_test                          (cached) PASSED in 1.2s
//prow/spyglass/lenses/buildlog:go_default_test                 (cached) PASSED in 1.4s
//prow/statusreconciler:go_default_test                         (cached) PASSED in 1.5s
//prow/test:integration-mkpj                                    (cached) PASSED in 4.0s
//prow/tide:go_default_test                                     (cached) PASSED in 30.0s
//prow/tide/blockers:go_default_test                            (cached) PASSED in 1.2s
//prow/tide/history:go_default_test                             (cached) PASSED in 1.4s
//robots/commenter:go_default_test                              (cached) PASSED in 1.5s
//robots/coverage/diff:go_default_test                          (cached) PASSED in 1.3s
//robots/issue-creator/creator:go_default_test                  (cached) PASSED in 1.2s
//robots/issue-creator/sources:go_default_test                  (cached) PASSED in 1.2s
//robots/issue-creator/testowner:go_default_test                (cached) PASSED in 1.2s
//scenarios:kubernetes_bazel_test                               (cached) PASSED in 0.2s
//scenarios:kubernetes_e2e_test                                 (cached) PASSED in 0.2s
//testgrid/cmd/configurator:go_default_test                     (cached) PASSED in 4.5s
//triage:berghelroach_test                                      (cached) PASSED in 15.2s
//triage:script_test                                            (cached) PASSED in 0.3s
//triage:summarize_test                                         (cached) PASSED in 1.5s
//velodrome:config_test                                         (cached) PASSED in 1.8s
//velodrome/fetcher:go_default_test                             (cached) PASSED in 1.6s
//velodrome/sql:go_default_test                                 (cached) PASSED in 1.3s
//velodrome/sql/testing:go_default_test                         (cached) PASSED in 1.2s
//velodrome/transform:go_default_test                           (cached) PASSED in 3.2s
//velodrome/transform/plugins:go_default_test                   (cached) PASSED in 1.2s
//hack:verify-pylint                                                     FAILED in 0.5s
  /usr/local/google/home/colew/.cache/bazel/_bazel_colew/5cc5e13b1337b342f46f1a99854b9e0c/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/testlogs/hack/verify-pylint/test.log

Executed 1 out of 200 tests: 199 tests pass and 1 fails locally.
INFO: Build completed, 1 test FAILED, 2 total actions
```

</details>

I suspect this is because there are no test files for the package and I used `bazel test //...` without `bazel build //...`, but given that the job uses the `test` command I feel like they should behave the same way. https://github.com/kubernetes/test-infra/blob/c8941d19219269f025278ea98a229b7e9c1a4acb/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L57-L60

/assign @fejta

**Comment by fejta** [comment]
Add `--nobuild_tests_only`
/close
