### ISSUE TITLE
Phaino will not start, complaining of a redefined flag

### ISSUE THREAD

**Issue by meowfaceman** [kubernetes/test-infra#14486]
**What happened**:

I installed phaino and it will not run.

**What you expected to happen**:

Phaino to run.

**How to reproduce it (as minimally and precisely as possible)**:

```
âžœ  release git:(SDAR-33) go version
go version go1.13 linux/amd64
âžœ  release git:(SDAR-33) go get k8s.io/test-infra/prow/cmd/phaino
âžœ  release git:(SDAR-33) phaino                                  
phaino flag redefined: log_dir
panic: phaino flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000098720, 0x1a92d40, 0xc00030f580, 0x18bcdb1, 0x7, 0x18e4ecd, 0x2f)
	/usr/lib/go/src/flag/flag.go:848 +0x4ae
flag.(*FlagSet).StringVar(...)
	/usr/lib/go/src/flag/flag.go:751
flag.(*FlagSet).String(0xc000098720, 0x18bcdb1, 0x7, 0x0, 0x0, 0x18e4ecd, 0x2f, 0xc00030f570)
	/usr/lib/go/src/flag/flag.go:764 +0xa0
flag.String(0x18bcdb1, 0x7, 0x0, 0x0, 0x18e4ecd, 0x2f, 0xc0000d5e30)
	/usr/lib/go/src/flag/flag.go:771 +0x69
github.com/tektoncd/pipeline/vendor/github.com/golang/glog.init()
	/home/mike/go/src/github.com/tektoncd/pipeline/vendor/github.com/golang/glog/glog_file.go:41 +0xd3
```

**Please provide links to example occurrences, if any**:

N/A

**Anything else we need to know?**:

I didn't do much here, it just flat out didn't work out of the box.

**Comment by stevekuznetsov** [comment]
xref #14320
