### ISSUE TITLE
Bad "Full PR test history" from PR builder in kops repo

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1449]
See https://github.com/kubernetes/kops/pull/1295#issuecomment-269518327 .. this comment has [Full PR test history](https://k8s-gubernator.appspot.com/pr/1295), but it should [Full PR test history](https://k8s-gubernator.appspot.com/pr/kops/1295).

We also seem to be missing results from that run, but the [test history](https://k8s-gubernator.appspot.com/pr/kops/1295) doesn't even show a build 307 despite the complaint.

**Comment by ixdy** [comment]
build 307 is missing because the git merge failed, and bootstrap.py didn't upload a log:

```
I1228 10:25:11.463] Call:  git checkout -B test 0a75e35171da5a29015ff16a510d923dba3f0590
W1228 10:25:13.683] Switched to a new branch 'test'
I1228 10:25:13.688] process 17468 exited with code 0
I1228 10:25:13.688] Call:  git merge --no-ff -m 'Merge +refs/pull/1295/head:refs/pr/1295' db31b621d934cc89dd2b5f2dc567342a6e3c670b
W1228 10:25:13.700] merge: db31b621d934cc89dd2b5f2dc567342a6e3c670b - not something we can merge
I1228 10:25:13.701] process 17469 exited with code 1
Traceback (most recent call last):
  File "./test-infra/jenkins/bootstrap.py", line 744, in <module>
    ARGS.service_account)
  File "./test-infra/jenkins/bootstrap.py", line 672, in bootstrap
    setup_root(root, repo, branch, pull)
  File "./test-infra/jenkins/bootstrap.py", line 660, in setup_root
    checkout(repo, branch, pull)
  File "./test-infra/jenkins/bootstrap.py", line 202, in checkout
    call(['git', 'merge', '--no-ff', '-m', 'Merge %s' % ref, head])
  File "./test-infra/jenkins/bootstrap.py", line 99, in call
    raise subprocess.CalledProcessError(code, cmd, lines)
subprocess.CalledProcessError: Command '['git', 'merge', '--no-ff', '-m', 'Merge +refs/pull/1295/head:refs/pr/1295', 'db31b621d934cc89dd2b5f2dc567342a6e3c670b']' returned non-zero exit status 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

This is usually caused by pushing new commits before the build starts, which is probably something that prow should report better. And bootstrap.py should also probably always upload a log, rather than having cases where it silently aborts.
