### ISSUE TITLE
Metric-bigquery job is failing due to ChunkedEncodingError.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#15036]
**What happened**:
https://k8s-testgrid.appspot.com/sig-testing-misc#metrics-bigquery
I think this is the relevant error text:
```
W1030 19:34:41.494] Traceback (most recent call last):
W1030 19:34:41.494]   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 685, in _update_chunk_length
W1030 19:34:41.494]     self.chunk_left = int(line, 16)
W1030 19:34:41.494] ValueError: invalid literal for int() with base 16: b''
W1030 19:34:41.494] 
W1030 19:34:41.494] During handling of the above exception, another exception occurred:
W1030 19:34:41.494] 
W1030 19:34:41.494] Traceback (most recent call last):
W1030 19:34:41.495]   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 425, in _error_catcher
W1030 19:34:41.495]     yield
W1030 19:34:41.495]   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 752, in read_chunked
W1030 19:34:41.495]     self._update_chunk_length()
W1030 19:34:41.495]   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 689, in _update_chunk_length
W1030 19:34:41.495]     raise httplib.IncompleteRead(line)
W1030 19:34:41.495] http.client.IncompleteRead: IncompleteRead(0 bytes read)
W1030 19:34:41.495] 
W1030 19:34:41.495] During handling of the above exception, another exception occurred:
W1030 19:34:41.495] 
W1030 19:34:41.496] Traceback (most recent call last):
W1030 19:34:41.496]   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 750, in generate
W1030 19:34:41.496]     for chunk in self.raw.stream(chunk_size, decode_content=True):
W1030 19:34:41.496]   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 560, in stream
W1030 19:34:41.496]     for line in self.read_chunked(amt, decode_content=decode_content):
W1030 19:34:41.496]   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 781, in read_chunked
W1030 19:34:41.496]     self._original_response.close()
W1030 19:34:41.496]   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
W1030 19:34:41.496]     self.gen.throw(type, value, traceback)
W1030 19:34:41.497]   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 443, in _error_catcher
W1030 19:34:41.497]     raise ProtocolError("Connection broken: %r" % e, e)
W1030 19:34:41.497] urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
W1030 19:34:41.497] 
W1030 19:34:41.497] During handling of the above exception, another exception occurred:
W1030 19:34:41.497] 
W1030 19:34:41.497] Traceback (most recent call last):
W1030 19:34:41.497]   File "test-infra/metrics/bigquery.py", line 250, in main
W1030 19:34:41.497]     queryer.run_metric(config)
W1030 19:34:41.498]   File "test-infra/metrics/bigquery.py", line 127, in run_metric
W1030 19:34:41.498]     self.update_query(config)
W1030 19:34:41.498]   File "test-infra/metrics/bigquery.py", line 174, in update_query
W1030 19:34:41.498]     'select last(%s), time from %s limit 1' % (field, measure)
W1030 19:34:41.498]   File "/usr/local/lib/python3.6/dist-packages/influxdb/client.py", line 416, in query
W1030 19:34:41.498]     expected_response_code=expected_response_code
W1030 19:34:41.498]   File "/usr/local/lib/python3.6/dist-packages/influxdb/client.py", line 267, in request
W1030 19:34:41.498]     timeout=self._timeout
W1030 19:34:41.498]   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
W1030 19:34:41.499]     resp = self.send(prep, **send_kwargs)
W1030 19:34:41.499]   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 686, in send
W1030 19:34:41.499]     r.content
W1030 19:34:41.499]   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 828, in content
W1030 19:34:41.499]     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
W1030 19:34:41.499]   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 753, in generate
W1030 19:34:41.501]     raise ChunkedEncodingError(e)
W1030 19:34:41.501] requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
```
I1030 19:36:15.353] Failed 1 configs: test-infra/metrics/configs/flakes-daily-config.yaml
E1030 19:36:15.353] Command failed
I1030 19:36:15.353] process 257 exited with code 1 after 4.2m
E1030 19:36:15.354] FAIL: metrics-bigquery
```
Any ideas about what could have caused this to start happening for 1 metric?

cc @clarketm @fejta @michelle192837

**Comment by fejta** [comment]
X uploading a new version of the file while Y is downloading it might cause this.

I suspect we should just retry here.

**Comment by clarketm** [comment]
Appears resolved: https://testgrid.k8s.io/sig-testing-misc#metrics-bigquery

/close
