### ISSUE TITLE
metrics-bigquery job failing on job-flakes-config.yaml query

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#15618]
**What happened**:
https://testgrid.k8s.io/sig-testing-misc#metrics-bigquery started failing 2019-12-12
- First failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/metrics-bigquery/1205303354364792832
- Most recent failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/metrics-bigquery/1206391063112060930

[It appears to be failing on a specific config](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/metrics-bigquery/1205303354364792832#1:build-log.txt%3A857)
```
Failed 1 configs: test-infra/metrics/configs/job-flakes-config.yaml
```

Other data is getting uploaded because dashboards in velodrome look fresh

**What you expected to happen**:
All queries to complete successfully

**Anything else we need to know?**:

**Comment by spiffxp** [comment]
```
W1216 01:51:08.433] Run: gsutil -h Cache-Control:max-age=60 cp raw-2019-12-16.json gs://k8s-metrics/job-flakes/raw-2019-12-16.json Run: jq '[(.[] | select(.job | contains("pr:")) | {(.job): {
W1216 01:51:08.433]     flakes: (.flakes|tonumber),
W1216 01:51:08.433]     runs: (.runs|tonumber),
W1216 01:51:08.433]     consistency: (.commit_consistency|tonumber)
W1216 01:51:08.433] }})] | add
W1216 01:51:08.433] ' raw-2019-12-16.json  > daily-2019-12-16.json
W1216 01:51:08.433] Traceback (most recent call last):
W1216 01:51:08.433]   File "test-infra/metrics/bigquery.py", line 250, in main
W1216 01:51:08.433]     queryer.run_metric(config)
W1216 01:51:08.434]   File "test-infra/metrics/bigquery.py", line 134, in run_metric
W1216 01:51:08.434]     consumer(config, raw)
W1216 01:51:08.434]   File "test-infra/metrics/bigquery.py", line 96, in jq_upload
W1216 01:51:08.434]     do_jq(config['jqfilter'], data_filename, filtered)
W1216 01:51:08.434]   File "test-infra/metrics/bigquery.py", line 65, in do_jq
W1216 01:51:08.434]     check([jq_bin, jq_filter, data_filename], stdout=out_file)
W1216 01:51:08.434]   File "test-infra/metrics/bigquery.py", line 50, in check
W1216 01:51:08.434]     subprocess.check_call(cmd, **kwargs)
W1216 01:51:08.434]   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
W1216 01:51:08.434]     raise CalledProcessError(retcode, cmd)
W1216 01:51:08.435] subprocess.CalledProcessError: Command '['jq', '[(.[] | select(.job | contains("pr:")) | {(.job): {\n    flakes: (.flakes|tonumber),\n    runs: (.runs|tonumber),\n    consistency: (.commit_consistency|tonumber)\n}})] | add\n', 'raw-2019-12-16.json']' returned non-zero exit status 5.
```

**Comment by spiffxp** [comment]
```
$ gsutil cp gs://k8s-metrics/job-flakes/raw-2019-12-13.json .
$ <raw-2019-12-13.json jq '[(.[] | select(.job | contains("pr:")) | {(.job): {
      flakes: (.flakes|tonumber),
      runs: (.runs|tonumber),
      consistency: (.commit_consistency|tonumber)
  }})] | add'
jq: error (at <stdin>:3461): null (null) cannot be parsed as a number
```
culprit data example:
```
{
    "build_consistency": "1.0", 
    "commit_consistency": null, 
    "flakes": "0", 
    "job": "pr:kubernetes-e2e-azure-disk-1-14", 
    "runs": "4"
  },
```

**Comment by spiffxp** [comment]
Possible workaround https://github.com/kubernetes/test-infra/pull/15619

Going to see if I can get rid of bad data first

**Comment by spiffxp** [comment]
/assign

bad data will age out, removed hold from pr
