### ISSUE TITLE
Pipeline (Tekton) extension for Prow is not working - pipeline pod is dying

### ISSUE THREAD

**Issue by ruzickap** [kubernetes/test-infra#16120]
**What happened**:

Image specified in the k8s manifest `gcr.io/k8s-testimages/pipeline:latest` for pipeline doesn't exists: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/pipeline/dev.yaml#L18

If I change it the image to `gcr.io/k8s-prow/pipeline` like:

```yaml
...
    spec:
      serviceAccount: prow-pipeline
      containers:
      - name: pipeline
        image: gcr.io/k8s-prow/pipeline:latest
---
```

then the pod is dying with this error:

```text
$ kubectl logs prow-pipeline-6cf5d55b4d-74rhs -n prow             
{"component":"pipeline","file":"prow/kube/config.go:147","func":"k8s.io/test-infra/prow/kube.LoadClusterConfigs","level":"info","msg":"Loading cluster contexts...","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/main.go:134","func":"main.main","level":"warning","msg":"Truncating to default context","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:148","func":"main.newController","level":"info","msg":"Setting up event handlers","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:202","func":"main.(*controller).Run","level":"info","msg":"Starting Pipeline controller","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:203","func":"main.(*controller).Run","level":"info","msg":"Waiting for informer caches to sync","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:106","func":"main.(*controller).hasSynced","level":"info","msg":"Synced prow jobs","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:120","func":"main.(*controller).hasSynced","level":"info","msg":"Synced default pipelines","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:208","func":"main.(*controller).Run","level":"info","msg":"Starting workers","time":"2020-02-04T13:03:44Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:213","func":"main.(*controller).Run","level":"info","msg":"Started workers","time":"2020-02-04T13:03:44Z"}
E0204 13:03:44.640162       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 82 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1493de0, 0x22f88b0)
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1493de0, 0x22f88b0)
        GOROOT/src/runtime/panic.go:679 +0x1b2
main.(*controller).pjNamespace(...)
        prow/cmd/pipeline/controller.go:88
main.(*controller).getProwJob(0xc0003b0120, 0xc00002a290, 0x24, 0x7, 0xc00002a288, 0x7)
        prow/cmd/pipeline/controller.go:294 +0x43
main.reconcile(0x18bbe60, 0xc0003b0120, 0xc00002a280, 0x34, 0xc000140e88, 0xc0006e7fe0)
        prow/cmd/pipeline/controller.go:370 +0x166
main.(*controller).runWorker.func1(0xc0003b0120, 0x141a240, 0xc0003cb0f0)
        prow/cmd/pipeline/controller.go:229 +0xd5
main.(*controller).runWorker(0xc0003b0120)
        prow/cmd/pipeline/controller.go:234 +0x2d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003cbaa0)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003cbaa0, 0x3b9aca00, 0x0, 0x45ec01, 0xc000322240)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003cbaa0, 0x3b9aca00, 0xc000322240)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by main.(*controller).Run
        prow/cmd/pipeline/controller.go:210 +0x294
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3d8 pc=0x1316493]

goroutine 82 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1493de0, 0x22f88b0)
        GOROOT/src/runtime/panic.go:679 +0x1b2
main.(*controller).pjNamespace(...)
        prow/cmd/pipeline/controller.go:88
main.(*controller).getProwJob(0xc0003b0120, 0xc00002a290, 0x24, 0x7, 0xc00002a288, 0x7)
        prow/cmd/pipeline/controller.go:294 +0x43
main.reconcile(0x18bbe60, 0xc0003b0120, 0xc00002a280, 0x34, 0xc000140e88, 0xc0006e7fe0)
        prow/cmd/pipeline/controller.go:370 +0x166
main.(*controller).runWorker.func1(0xc0003b0120, 0x141a240, 0xc0003cb0f0)
        prow/cmd/pipeline/controller.go:229 +0xd5
main.(*controller).runWorker(0xc0003b0120)
        prow/cmd/pipeline/controller.go:234 +0x2d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003cbaa0)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003cbaa0, 0x3b9aca00, 0x0, 0x45ec01, 0xc000322240)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003cbaa0, 0x3b9aca00, 0xc000322240)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by main.(*controller).Run
        prow/cmd/pipeline/controller.go:210 +0x294
```

**What you expected to happen**:

Pod should be started successfully without errors mentioned above. 

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/test-infra/master/prow/cmd/pipeline/dev.yaml

# Then you can edit the pod and replace the image with `gcr.io/k8s-prow/pipeline:latest`

$ kubectl edit pod prow-pipeline-6cf5d55b4d-74rhs
```

This issue may be related to these issues, where it's "described" how to run Tekton + Prow:

* https://github.com/kubernetes/test-infra/issues/13874
* https://github.com/tektoncd/pipeline/issues/1187

Thanks for looking at it...

**Comment by eddycharly** [comment]
I think these docs are pretty outdated, tekton pipeline changed a lot during the last months and i am not sure the docs were kept up to date on either prow or tekton side.

There is an open PR to use the latest tekton version in prow (https://github.com/kubernetes/test-infra/pull/16099).

Might be a good time to refresh the docs. I'll try to take time to do it, in the meantime you can ask questions here, i'll try to help.

**Comment by ruzickap** [comment]
Thank you for the quick update...
I'll wait for the #16099 to be merged and then I'll try to make it running again.
Updated docs are always welcome :-)

**Comment by ruzickap** [comment]
Hi @eddycharly - thank you for your #16099 - it was merged so I tried to install fresh k8s cluster with latest prow and latest (0.10.1) Tekton.

Unfortunately the `prow-pipeline` is still crushing. 

If I trigger the test action from GitHub PR chat (using `/run test`), the prow hook pod will create the prow job (`0f883c49-4d78-11ea-8c2d-36c7d32758f7`) properly:

```bash
$ kubectl logs -n prow hook-67dfb85f85-w26jv -f 
...
{"author":"ruzickap","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/hook/events.go:322","func":"k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent","level":"info","msg":"Issue comment created.","org":"Mirantis","pr":1,"repo":"magma","time":"2020-02-12T09:14:22Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:527","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"IsCollaborator(Mirantis, ruzickap)","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:22Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","duration":"216.351927ms","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:529","func":"k8s.io/test-infra/prow/github.(*client).log.func2","level":"debug","msg":"IsCollaborator(Mirantis, ruzickap) finished","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:22Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:527","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetIssueLabels(Mirantis, magma, 1)","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:22Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","duration":"522.209016ms","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:529","func":"k8s.io/test-infra/prow/github.(*client).log.func2","level":"debug","msg":"GetIssueLabels(Mirantis, magma, 1) finished","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:23Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:527","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetPullRequest(Mirantis, magma, 1)","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:23Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","duration":"710.536037ms","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:529","func":"k8s.io/test-infra/prow/github.(*client).log.func2","level":"debug","msg":"GetPullRequest(Mirantis, magma, 1) finished","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:23Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:527","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetRef(Mirantis, magma, heads/master)","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:23Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","client":"github","component":"hook","duration":"197.502826ms","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/github/client.go:529","func":"k8s.io/test-infra/prow/github.(*client).log.func2","level":"debug","msg":"GetRef(Mirantis, magma, heads/master) finished","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:24Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/pjutil/filter.go:101","func":"k8s.io/test-infra/prow/pjutil.FilterPresubmits","level":"debug","msg":"Filtered 1 jobs, found 1 to trigger and 0 to skip.","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:24Z","to-skip":null,"to-trigger":["magma-test"],"url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/plugins/trigger/trigger.go:241","func":"k8s.io/test-infra/prow/plugins/trigger.runRequested","level":"info","msg":"Starting magma-test build.","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:24Z","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
{"author":"ruzickap","component":"hook","event-GUID":"0dbb1480-4d78-11ea-96cc-7c54c3b3a912","event-type":"issue_comment","file":"prow/plugins/trigger/trigger.go:243","func":"k8s.io/test-infra/prow/plugins/trigger.runRequested","job":"magma-test","level":"info","msg":"Creating a new prowjob.","name":"0f883c49-4d78-11ea-8c2d-36c7d32758f7","org":"Mirantis","plugin":"trigger","pr":1,"repo":"magma","time":"2020-02-12T09:14:24Z","type":"presubmit","url":"https://github.com/Mirantis/magma/pull/1#issuecomment-585106878"}
```

The newly created prowjob looks also fine:

```bash
$ kubectl describe prowjobs.prow.k8s.io -n prowjob 0f883c49-4d78-11ea-8c2d-36c7d32758f7 
Name:         0f883c49-4d78-11ea-8c2d-36c7d32758f7
Namespace:    prowjob
Labels:       created-by-prow=true
              event-GUID=0dbb1480-4d78-11ea-96cc-7c54c3b3a912
              prow.k8s.io/job=magma-test
              prow.k8s.io/refs.org=Mirantis
              prow.k8s.io/refs.pull=1
              prow.k8s.io/refs.repo=magma
              prow.k8s.io/type=presubmit
Annotations:  prow.k8s.io/job: magma-test
API Version:  prow.k8s.io/v1
Kind:         ProwJob
Metadata:
  Creation Timestamp:  2020-02-12T09:14:24Z
  Generation:          1
  Resource Version:    197722
  Self Link:           /apis/prow.k8s.io/v1/namespaces/prowjob/prowjobs/0f883c49-4d78-11ea-8c2d-36c7d32758f7
  UID:                 0147d667-781b-48ad-8797-edaa0b74ced0
Spec:
  Agent:      tekton-pipeline
  Cluster:    default
  Context:    magma-test
  Job:        magma-test
  Namespace:  prowjob
  pipeline_run_spec:
    Pipeline Ref:
      Name:  magma-pipeline
    Resources:
      Name:  git-repo
      Resource Ref:
        Name:  PROW_IMPLICIT_GIT_REF
  Refs:
    base_link:  https://github.com/Mirantis/magma/commit/c9207c1964b313eb4f94c48f259c7692083a9ee5
    base_ref:   master
    base_sha:   c9207c1964b313eb4f94c48f259c7692083a9ee5
    Org:        Mirantis
    Pulls:
      Author:       ruzickap
      author_link:  https://github.com/ruzickap
      commit_link:  https://github.com/Mirantis/magma/pull/1/commits/cee6c68828a76b63c2c4ae878c553f3e889a6379
      Link:         https://github.com/Mirantis/magma/pull/1
      Number:       1
      Sha:          cee6c68828a76b63c2c4ae878c553f3e889a6379
    Repo:           magma
    repo_link:      https://github.com/Mirantis/magma
  Report:           true
  rerun_auth_config:
  rerun_command:  /run test
  Type:           presubmit
Status:
  Start Time:  2020-02-12T09:14:24Z
  State:       triggered
Events:        <none>
```

But the `prow-pipeline` immediately died when I the prowjob was created:

```bash
$ kubectl logs -n prow prow-pipeline-bc9f9b88b-vxmdv -f 
{"component":"pipeline","file":"prow/kube/config.go:147","func":"k8s.io/test-infra/prow/kube.LoadClusterConfigs","level":"info","msg":"Loading cluster contexts...","time":"2020-02-11T15:12:54Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/main.go:142","func":"main.main","level":"warning","msg":"Truncating to default context","time":"2020-02-11T15:12:54Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:148","func":"main.newController","level":"info","msg":"Setting up event handlers","time":"2020-02-11T15:12:56Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:202","func":"main.(*controller).Run","level":"info","msg":"Starting Pipeline controller","time":"2020-02-11T15:12:56Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:203","func":"main.(*controller).Run","level":"info","msg":"Waiting for informer caches to sync","time":"2020-02-11T15:12:56Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:106","func":"main.(*controller).hasSynced","level":"info","msg":"Synced prow jobs","time":"2020-02-11T15:12:56Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:120","func":"main.(*controller).hasSynced","level":"info","msg":"Synced default pipelines","time":"2020-02-11T15:12:56Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:208","func":"main.(*controller).Run","level":"info","msg":"Starting workers","time":"2020-02-11T15:12:56Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:213","func":"main.(*controller).Run","level":"info","msg":"Started workers","time":"2020-02-11T15:12:56Z"}


E0212 09:14:24.089763       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 68 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14bfba0, 0x234ddb0)
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x14bfba0, 0x234ddb0)
        GOROOT/src/runtime/panic.go:679 +0x1b2
main.(*controller).pjNamespace(...)
        prow/cmd/pipeline/controller.go:88
main.(*controller).getProwJob(0xc0000fa630, 0xc00035a4d0, 0x24, 0x7, 0xc00035a4c8, 0x7)
        prow/cmd/pipeline/controller.go:294 +0x43
main.reconcile(0x18f2b40, 0xc0000fa630, 0xc00035a4c0, 0x34, 0xc000142e88, 0xc000630850)
        prow/cmd/pipeline/controller.go:370 +0x166
main.(*controller).runWorker.func1(0xc0000fa630, 0x1445080, 0xc00003bc20)
        prow/cmd/pipeline/controller.go:229 +0xd5
main.(*controller).runWorker(0xc0000fa630)
        prow/cmd/pipeline/controller.go:234 +0x2d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000639140)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000639140, 0x3b9aca00, 0x0, 0x1, 0xc00037e300)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000639140, 0x3b9aca00, 0xc00037e300)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by main.(*controller).Run
        prow/cmd/pipeline/controller.go:210 +0x294
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3d8 pc=0x133d3b3]

goroutine 68 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x14bfba0, 0x234ddb0)
        GOROOT/src/runtime/panic.go:679 +0x1b2
main.(*controller).pjNamespace(...)
        prow/cmd/pipeline/controller.go:88
main.(*controller).getProwJob(0xc0000fa630, 0xc00035a4d0, 0x24, 0x7, 0xc00035a4c8, 0x7)
        prow/cmd/pipeline/controller.go:294 +0x43
main.reconcile(0x18f2b40, 0xc0000fa630, 0xc00035a4c0, 0x34, 0xc000142e88, 0xc000630850)
        prow/cmd/pipeline/controller.go:370 +0x166
main.(*controller).runWorker.func1(0xc0000fa630, 0x1445080, 0xc00003bc20)
        prow/cmd/pipeline/controller.go:229 +0xd5
main.(*controller).runWorker(0xc0000fa630)
        prow/cmd/pipeline/controller.go:234 +0x2d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000639140)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000639140, 0x3b9aca00, 0x0, 0x1, 0xc00037e300)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000639140, 0x3b9aca00, 0xc00037e300)
        external/io_k8s_apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by main.(*controller).Run
        prow/cmd/pipeline/controller.go:210 +0x294
```

I can see the the `prow-pipeline` is constantly restarting because of the error mentioned above:

```bash
$ kubectl get pod -n prow prow-pipeline-bc9f9b88b-vxmdv
NAME                            READY   STATUS             RESTARTS   AGE
prow-pipeline-bc9f9b88b-vxmdv   0/1     CrashLoopBackOff   7          18h
```

I can see other people are also trying to make the Tekton 0.10.1 working: https://github.com/kubernetes/test-infra/pull/13974 but there is no documentation about it.

I can only use this to set prow+tekton up: https://github.com/kubernetes/test-infra/issues/13874#issuecomment-521237150

Please let me know if you can find out why the `prow-pipeline` is crashing or if you can reproduce the issue (or if there is any "recent documentation" how to make it running).

Thank you...

**Comment by eddycharly** [comment]
@ruzickap I'll have a look at the docs today. Sorry for the late reply I was on vacation.

**Comment by eddycharly** [comment]
From what i see, the issue you have is related to the the prow config not being set on the command line.
You could try to adapt your manifest to look like this :
```yaml
          args:
            - --all-contexts
            - --config=/etc/prow-config/config.yaml
          volumeMounts:
            - mountPath: /etc/prow-config
              name: prow-config
              readOnly: true
      volumes:
        - name: prow-config
          configMap:
            name: config
```

**Comment by ruzickap** [comment]
Thanks a lot @eddycharly. 
You are right - this was missing from my `prow-pipeline` deployment definition. 

It would be nice if the pod will tell me something like "missing config" instead of crashing. 
Anyway - after adding the "config lines" - it stopped crashing.

Thanks again...

**Comment by eddycharly** [comment]
You're welcome, we are currently discussing it here https://github.com/kubernetes/test-infra/pull/16323

**Comment by ruzickap** [comment]
Awesome :-)

Good luck...
