### ISSUE TITLE
sig-node tests failing "error converting YAML to JSON"

### ISSUE THREAD

**Issue by karan** [kubernetes/test-infra#17816]
https://testgrid.k8s.io/sig-node-containerd#node-e2e
https://testgrid.k8s.io/sig-node-containerd#node-e2e-features
https://testgrid.k8s.io/sig-node-containerd#node-e2e-flaky
https://testgrid.k8s.io/sig-node-containerd#node-e2e-serial

```
W0602 21:35:20.137] F0602 21:35:20.137485    4744 run_remote.go:235] Could not parse image config file: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
W0602 21:35:20.138] goroutine 1 [running]:
W0602 21:35:20.138] k8s.io/klog/v2.stacks(0xc0000e0001, 0xc0001ce300, 0xb0, 0xfe)
W0602 21:35:20.138] 	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:972 +0xb8
W0602 21:35:20.138] k8s.io/klog/v2.(*loggingT).output(0x2986fc0, 0xc000000003, 0x0, 0x0, 0xc0002193b0, 0x28ec9ee, 0xd, 0xeb, 0x0)
W0602 21:35:20.139] 	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:921 +0x19d
W0602 21:35:20.139] k8s.io/klog/v2.(*loggingT).printf(0x2986fc0, 0x3, 0x0, 0x0, 0x1abdd3c, 0x25, 0xc00063b550, 0x1, 0x1)
W0602 21:35:20.139] 	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:733 +0x17a
W0602 21:35:20.139] k8s.io/klog/v2.Fatalf(...)
W0602 21:35:20.139] 	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1427
W0602 21:35:20.139] main.main()
W0602 21:35:20.140] 	/go/src/k8s.io/kubernetes/test/e2e_node/runner/remote/run_remote.go:235 +0x53d
W0602 21:35:20.140] 
W0602 21:35:20.140] goroutine 19 [chan receive]:
W0602 21:35:20.140] k8s.io/klog/v2.(*loggingT).flushDaemon(0x2986fc0)
W0602 21:35:20.140] 	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
W0602 21:35:20.140] created by k8s.io/klog/v2.init.0
W0602 21:35:20.141] 	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd6
W0602 21:35:20.141] 
W0602 21:35:20.141] goroutine 67 [select]:
W0602 21:35:20.141] go.opencensus.io/stats/view.(*worker).start(0xc0003ee870)
W0602 21:35:20.141] 	/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:154 +0x100
W0602 21:35:20.141] created by go.opencensus.io/stats/view.init.0
W0602 21:35:20.141] 	/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:32 +0x57
W0602 21:35:20.142] exit status 255
```

They are tracked in https://docs.google.com/spreadsheets/d/1mEU8B2_PmMwwgp-_xnyp7QYMBwcLoA9NNlHwDyMvO0Y/edit#gid=0.

/kind cleanup
/sig node
/sig testing
/assign karan

**Comment by karan** [comment]
Thanks for fixing!

And just for tracking (although idk if that matters)
/assign @MHBauer
