### ISSUE TITLE
ci-test-infra-triage (triage clustering) is failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#18983]
**What happened**:

https://prow.k8s.io/?job=*triage* is failing consistently

**What you expected to happen**:

triage should be succeeding

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-triage/1298307826921246720

```
Operation completed over 3 objects/74.1 MiB.                                     
+ gzip -df triage_tests/shard_000000000000.json.gz triage_tests/shard_000000000001.json.gz triage_tests/shard_000000000002.json.gz
+ mkdir -p slices
+ /triage --builds triage_builds.json --tests triage_tests/shard_000000000000.json triage_tests/shard_000000000001.json triage_tests/shard_000000000002.json --output failure_data.json --output_slices slices/failure_data_PREFIX.json --num_workers 7
F0825 17:16:24.059704     141 summarize.go:65] 'PREFIX' not in output_slices flag
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc0000a8001, 0xc0000f2000, 0x52, 0xa2)
	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:972 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x669500, 0xc000000003, 0x0, 0x0, 0xc0000d64d0, 0x64db91, 0xc, 0x41, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:921 +0x19d
k8s.io/klog/v2.(*loggingT).printf(0x669500, 0x3, 0x0, 0x0, 0x56b62a, 0x22, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1427
k8s.io/test-infra/triage/summarize.parseFlags(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/test-infra/triage/summarize/summarize.go:65 +0x4bc
k8s.io/test-infra/triage/summarize.Main()
	/test-infra/triage/summarize/summarize.go:166 +0x30
main.main()
	/test-infra/triage/main.go:22 +0x20
goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x669500)
	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
created by k8s.io/klog/v2.init.0
	/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd6

```

**Comment by BenTheElder** [comment]
Found it
/assign

**Comment by BenTheElder** [comment]
It's runing but still trying to catch up I think https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-triage/1298339004017545219

**Comment by BenTheElder** [comment]
It's now failing because it takes too long, probably because it has too much catching up to do.

**Comment by BenTheElder** [comment]
while the job timed out it managed to upload results during the 15m timeout, so the dashboard is updated at least. filed https://github.com/kubernetes/test-infra/pull/18991

**Comment by BenTheElder** [comment]
This has passed twice now but is still going slower than you would hope.

**Comment by BenTheElder** [comment]
Discussed disabling memoize in CI

**Comment by BenTheElder** [comment]
Still slower than ideal but that's not this issue.
