### ISSUE TITLE
Investigate 'unknown build path' failures in Kettle

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19367]
**What happened**:
Kettle make_json is dumping many
```
ERROR:root:error on gs://k8s-conformance-gardener/ci-gardener-e2e-conformance-alicloud-v1.16/1600618556
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 253, in row_for_build
    build = Build.generate(path, tests, started, finished, metadata, repos)
  File "make_json.py", line 93, in generate
    build = cls(path, tests)
  File "make_json.py", line 89, in __init__
    self.populate_path_to_job_and_number()
  File "make_json.py", line 110, in populate_path_to_job_and_number
    raise ValueError('unknown build path')
ValueError: unknown build path
ERROR:root:error on gs://compute-image-tools-test/logs/osconfig-unstable/1307701327609991168
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 253, in row_for_build
    build = Build.generate(path, tests, started, finished, metadata, repos)
  File "make_json.py", line 93, in generate
    build = cls(path, tests)
  File "make_json.py", line 89, in __init__
    self.populate_path_to_job_and_number()
  File "make_json.py", line 110, in populate_path_to_job_and_number
    raise ValueError('unknown build path')
ValueError: unknown build path
```
Errors while trying to populate builds. This might be expected but should most likely not trace back this much or dump all failed buckets once at the end.

/area kettle
/assign
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Run `pypy3 make_json.py` from kettle

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
[Logs Link (internal)](https://pantheon.corp.google.com/logs/viewer?project=k8s-gubernator&minLogLevel=0&expandAll=false&timestamp=2020-09-25T03:22:43.108000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-09-25T02:22:43.362Z&dateRangeEnd=2020-09-25T03:22:43.362Z&interval=PT1H&resource=k8s_container%2Fcluster_name%2Fg8r%2Fnamespace_name%2Fdefault%2Fcontainer_name%2Fkettle&scrollTimestamp=2020-09-25T02:53:48.239065595Z)

**Comment by MushuEE** [comment]
Along with this failure: 
```
ERROR:root:error on gs://kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-host-path/202/pull-kubernetes-csi-csi-driver-host-path-unit/1309666950472798208
Traceback (most recent call last):
  File "make_json.py", line 278, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 218, in row_for_build
    for test in parse_junit(result):
  File "make_json.py", line 139, in parse_junit
    time, failure_text, skipped = parse_result(child)
  File "make_json.py", line 129, in parse_result
    time = float(child_node.attrib.get('time', 0))
ValueError: could not convert string to float: ''
ERROR:root:error on gs://kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-host-path/202/pull-kubernetes-csi-csi-driver-host-path-unit/1309688692251561984
Traceback (most recent call last):
  File "make_json.py", line 278, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 218, in row_for_build
    for test in parse_junit(result):
  File "make_json.py", line 139, in parse_junit
    time, failure_text, skipped = parse_result(child)
  File "make_json.py", line 129, in parse_result
    time = float(child_node.attrib.get('time', 0))
ValueError: could not convert string to float: ''
```

and

```
ERROR:root:error on gs://kubernetes-jenkins/logs/e2e-kops-grid-kopeio-flatcar-k17-ko18/1309206939384680448
Traceback (most recent call last):
  File "/opt/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/xml/etree/ElementTree.py", line 1624, in feed
    self.parser.Parse(data, 0)
pyexpat.ExpatError: not well-formed (invalid token): line 224, column 161

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_json.py", line 278, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 218, in row_for_build
    for test in parse_junit(result):
  File "make_json.py", line 111, in parse_junit
    tree = ET.fromstring(xml)
  File "/opt/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "/opt/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/xml/etree/ElementTree.py", line 1626, in feed
    self._raiseerror(v)
  File "/opt/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/xml/etree/ElementTree.py", line 1525, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 224, column 161
```
