### ISSUE TITLE
Kettle Prod failing to decode data

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19732]
**What happened**:
Some file paths seem to have corrupt data with the database:
```
Error while reading data, error message: JSON parsing error in row starting at position 1286510561: Parser terminated before end of string

Error while reading data, error message: JSON parsing error in row starting at position 1945315794: Could not parse value

ERROR:root:error on gs://kubernetes-jenkins/pr-logs/pull/57600/pull-kubernetes-verify/84123
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    results = db.test_results_for_build(path)
  File "/kettle/model.py", line 167, in test_results_for_build
    data = zlib.decompress(dataz).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 1147: invalid start byte
ERROR:root:error on gs://kubernetes-jenkins/pr-logs/pull/57600/pull-kubernetes-verify/84147
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    results = db.test_results_for_build(path)
  File "/kettle/model.py", line 167, in test_results_for_build
    data = zlib.decompress(dataz).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 2874: invalid start byte
ERROR:root:error on gs://pivotal-e2e-results/kubo-windows-2019/1553782223
Traceback (most recent call last):
  File "make_json.py", line 281, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 254, in row_for_build
    build = Build.generate(path, tests, started, finished, metadata, repos)
  File "make_json.py", line 94, in generate
    build = cls(path, tests)
  File "make_json.py", line 90, in __init__
    self.populate_path_to_job_and_number()
  File "make_json.py", line 112, in populate_path_to_job_and_number
    raise ValueError(f'unknown build path for {self.path} in known bucket paths')
ValueError: unknown build path for gs://pivotal-e2e-results/kubo-windows-2019/1553782223 in known bucket paths
ERROR:root:error on gs://kubernetes-jenkins/pr-logs/pull/77766/pull-kubernetes-dependencies-canary/1127001638385487872
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    results = db.test_results_for_build(path)
  File "/kettle/model.py", line 167, in test_results_for_build
    data = zlib.decompress(dataz).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 7073533: invalid start byte
ERROR:root:error on gs://kubernetes-jenkins/pr-logs/pull/77766/pull-kubernetes-dependencies/1127001638381293569
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    results = db.test_results_for_build(path)
  File "/kettle/model.py", line 167, in test_results_for_build
    data = zlib.decompress(dataz).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 7073533: invalid start byte
ERROR:root:error on gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-cos-containerd-gke-k8sstable1-alpha-cluster/1180870216318455809
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    results = db.test_results_for_build(path)
  File "/kettle/model.py", line 166, in test_results_for_build
    (path, path + '\x7F')):
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 419, in execute
    return cur.execute(*args)
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 773, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 934, in execute
    return self.__execute(False, sql, [params])
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 889, in __execute
    self.__statement._set_params(params)
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 1180, in _set_params
    "probably unsupported type." % i)
_sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```
[Thread about issue](https://stackoverflow.com/questions/21231264/python-sqlite-interfaceerror-error-binding-parameter-0-probably-unsupported)

**What you expected to happen**:
Kettle cleanly parses and exports the database results. 
**How to reproduce it (as minimally and precisely as possible)**:
Run prod kettle with a newer version
Follow logs
**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
This is happening in 
```
    def test_results_for_build(self, path):
        """
        Return a list of file data under the given path. Intended for JUnit artifacts.
        """
        results = []
        for dataz, in self.db.execute(
                'select data from file where path between ? and ?',
                (path, path + '\x7F')):
            data = zlib.decompress(dataz).decode('utf-8')
            if data:
                results.append(data)
        return results
```
You can drop in and execute this manually if you really want to.

/area kettle
/assign

**Comment by MushuEE** [comment]
I was unable to duplicate this manually... Unsure what the difference might be

**Comment by MushuEE** [comment]
```
def row_to_mapping(row, schema):
    """Convert a dictionary to a list for bigquery.Table.insert_data.

    Silly. See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3396
    """
    return [row.get(field.name, [] if field.mode == 'REPEATED' else None) for field in schema]
```
Old Row to mapping... maybe linked?

**Comment by MushuEE** [comment]
```
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    results = db.test_results_for_build(path)
  File "/kettle/model.py", line 168, in test_results_for_build
    (path, path + '\x7F')):
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 419, in execute
    return cur.execute(*args)
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 773, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 934, in execute
    return self.__execute(False, sql, [params])
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 889, in __execute
    self.__statement._set_params(params)
  File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 1180, in _set_params
    "probably unsupported type." % i)
_sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
client_loop: send disconnect: Broken pipe
```
Still occurring. Maybe dig deeper into the DB to discover issues

**Comment by MushuEE** [comment]
Was able to repro manually:
```
>>> job = "gs://kubernetes-jenkins/pr-logs/pull/77766/pull-kubernetes-dependencies-canary/1127001638385487872"
>>> x = db.execute('select data from file where path between ? and ?', (job, job + '\x7F'))
>>> for i, in x:
...     zlib.decompress(i).decode('utf-8')
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 7073533: invalid start byte
```

**Comment by MushuEE** [comment]
```
>>> x = db.execute('select data from file where path between ? and ?', (job, job + '\x7F'))
>>> for i, in x:
...     chardet.detect(zlib.decompress(i))
...

{'encoding': 'Windows-1254', 'confidence': 0.5059954622216586, 'language': 'Turkish'}
```

**Comment by MushuEE** [comment]
Still seeing several
```
2020-11-21T18:09:52.481661453Z ERROR:root:error on gs://kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1330097614166691840
2020-11-21T18:09:52.481707706Z Traceback (most recent call last):
2020-11-21T18:09:52.481714924Z   File "make_json.py", line 280, in make_rows
2020-11-21T18:09:52.481720584Z     results = db.test_results_for_build(path)
2020-11-21T18:09:52.481726561Z   File "/kettle/model.py", line 168, in test_results_for_build
2020-11-21T18:09:52.481732515Z     (path, path + '\x7F')):
2020-11-21T18:09:52.4817388Z   File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 419, in execute
2020-11-21T18:09:52.481745025Z     return cur.execute(*args)
2020-11-21T18:09:52.481750351Z   File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 773, in wrapper
2020-11-21T18:09:52.481756132Z     return func(self, *args, **kwargs)
2020-11-21T18:09:52.481761554Z   File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 934, in execute
2020-11-21T18:09:52.481767143Z     return self.__execute(False, sql, [params])
2020-11-21T18:09:52.481772438Z   File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 889, in __execute
2020-11-21T18:09:52.481777624Z     self.__statement._set_params(params)
2020-11-21T18:09:52.481782571Z   File "/opt/pypy3.6-v7.3.1-linux64/lib_pypy/_sqlite3.py", line 1180, in _set_params
2020-11-21T18:09:52.481787838Z     "probably unsupported type." % i)
2020-11-21T18:09:52.481793106Z _sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```
