### ISSUE TITLE
[Kettle] Streaming build data sometimes results in JSON error

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#20236]
**What happened**:
During the data stream process, 
```
ERROR:root:Failed to decode request for kubernetes-jenkins/o/pr-logs%2Fpull%2Fkubeflow_pipelines%2F4885%2Fkubeflow-pipeline-backend-test%2F1336900731344523264%2Ffinished.json
Traceback (most recent call last):
  File "/kettle/make_db.py", line 67, in _request
    return resp.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
**What you expected to happen**:
Build that fail to decode Json are logged and skipped

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to pull from above path `kubernetes-jenkins/o/pr-logs%2Fpull%2Fkubeflow_pipelines%2F4885%2Fkubeflow-pipeline-backend-test%2F1336900731344523264%2Ffinished.json`

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
Looks like there is a possibility the paths are getting poorly decoded. 
`https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4861/kubeflow-pipeline-backend-test/1338602622315139072/finished.json`
vs
`kubernetes-jenkins/o/pr-logs%2Fpull%2Fkubeflow_pipelines%2F4885%2Fkubeflow-pipeline-backend-test%2F1336900731344523264%2Ffinished.json
Traceback (most recent call last):`

**Comment by MushuEE** [comment]
It looks like the request if getting nothing:
```
>>> import requests
>>> r = requests.Session()
>>> r.get(uri, params={'alt': 'media'})
<Response [200]>
>>> resp = r.get(uri, params={'alt': 'media'})
>>> resp.json()
Failure
>>> resp.text
''
```
While `curl https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2Fkubeflow_pipelines%2F4885%2Fkubeflow-pipeline-backend-test%2F1336900731344523264%2Ffinished.json` works fine

**Comment by MushuEE** [comment]
```
>>> uri = "https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4861/kubeflow-pipeline-backend-test/1338602622315139072/finished.json"
>>> resp = r.get(uri, params={})
>>> resp.json()
{'timestamp': 1607982968, 'passed': True, 'result': 'SUCCESS', 'revision': 'fe11c36efd624bfd5decfb680909ce9281c724d4'}
```
This does work if the url is not quoted and use the base path `https://storage.googleapis.com/kubernetes-jenkins/`

**Comment by MushuEE** [comment]
There seem to be two cases for data, some paths that have object data only and some that have metadata. If a path has metadata and `alt`:`media` is not used, we get object metadata. However if we get a path without, it will return nothing.

**Comment by MushuEE** [comment]
Turns out this seems to be an issue with the exact end point: 
```
>>> uri2
'https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4861/kubeflow-pipeline-backend-test/1338602622315139072/finished.json'
>>> uri3
'https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2Fkubeflow_pipelines%2F4885%2Fkubeflow-pipeline-backend-test%2F1336900731344523264%2Ffinished.json'
```
uri2 works where uri3 does not.

**Comment by MushuEE** [comment]
This change will be good because it will also update the end point

**Comment by MushuEE** [comment]
I was mistaken: the object is actually empty
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4885/kubeflow-pipeline-backend-test/1336900731344523264/finished.json
