### ISSUE TITLE
[Kettle] Streaming BQ results issuing "illegal requests"

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#20307]
**What happened**:
Kettle was updated to surpass the production lockup it was hitting due to Database growth and it has been some time since it was successful in executing a stream PubSub process. It appears this process is now failing due to `Your client has issued a malformed or illegal request.  <ins>That\u2019s all we know.</ins>`

```
Traceback (most recent call last):
  File "stream.py", line 310, in <module>
    stop=StopWhen(OPTIONS.stop_at))
  File "stream.py", line 204, in main
    emitted = insert_data(bq_client, table, make_json.make_rows(db, builds))
  File "stream.py", line 124, in insert_data
    errors = retry(bq_client.insert_rows, table, rows, skip_invalid_rows=True)
  File "stream.py", line 95, in retry
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/client.py", line 2869, in insert_rows
    return self.insert_rows_json(table, json_rows, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/client.py", line 3016, in insert_rows_json
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/client.py", line 636, in _call_api
    return call()
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/_http.py", line 438, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/k8s-gubernator/datasets/build/tables/all/insertAll?prettyPrint=false: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That\u2019s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That\u2019s all we know.</ins>
``` 

**What you expected to happen**:
BQ client uploads should pass successfully.

**How to reproduce it (as minimally and precisely as possible)**:
You can drop into the container and manually run the script `python3 stream.py --poll kubernetes-jenkins/gcs-changes/kettle  --dataset k8s-gubernator:build --tables all:0 day:1 week:7 --stop_at=1`

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/area kettle
/cc @amwat 
/assign

**Comment by MushuEE** [comment]
Seeing new failure:
```
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/k8s-gubernator/datasets/build/tables/all/insertAll?prettyPrint=false: Request payload size exceeds the limit: 10485760 bytes.
```

**Comment by amwat** [comment]
I thought we reduced the amount of build emitted by limiting it to past 30 days?

**Comment by MushuEE** [comment]
^ We did, because the stream emitted table was not using the 30 day table it was trying to add in more builds than it should have which was causing this failure.
