### ISSUE TITLE
Kettle seeing "Bad Request" in BQ insert 

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#20606]
**What happened**:
Kettle staging is seeing `Bad Requests` when trying to stream data to BQ, this is not the behavior seen within Prod.
 
```
Traceback (most recent call last):
  File "stream.py", line 318, in <module>
    stop=StopWhen(OPTIONS.stop_at))
  File "stream.py", line 212, in main
    emitted = insert_data(bq_client, table, make_json.make_rows(db, builds))
  File "stream.py", line 132, in insert_data
    errors = retry(bq_client.insert_rows, table, chunk, skip_invalid_rows=True)
  File "stream.py", line 96, in retry
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/client.py", line 2869, in insert_rows
    return self.insert_rows_json(table, json_rows, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/client.py", line 3016, in insert_rows_json
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/client.py", line 636, in _call_api
    return call()
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/_http.py", line 438, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/k8s-gubernator/datasets/build/tables/staging/insertAll?prettyPrint=false: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That\u2019s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That\u2019s all we know.</ins>

+ time python3 make_db.py --buckets buckets.yaml --junit --threads 32
+ pypy3 make_json.py --days 1 --assert-oldest 1.9
+ pypy3 make_json.py | pv | gzip > build_staging.json.gz
+ bq load --source_format=NEWLINE_DELIMITED_JSON --max_bad_records=1000 k8s-gubernator:build.staging build_staging.json.gz schema.json
+ python3 stream.py --poll kubernetes-jenkins/gcs-changes/kettle-staging --dataset k8s-gubernator:build --tables staging:0 --stop_at=1
Traceback (most recent call last):
  File "/kettle/update.py", line 86, in <module>
    main()
  File "/kettle/update.py", line 80, in main
    call(f'python3 stream.py --poll {SUB_PATH} ' \
  File "/kettle/update.py", line 44, in call
    raise OSError('invocation failed')
OSError: invocation failed
```
**What you expected to happen**:
BQ inserts pass or don't occur at all if data is malformed.

**How to reproduce it (as minimally and precisely as possible)**:
Run the stream.py from the staging ENV

**Please provide links to example occurrences, if any**:
`kubectl logs -f kettle-staging-76dbcdb95c-qgw8n -p` 

**Anything else we need to know?**:
/area kettle
/assign

**Comment by MushuEE** [comment]
Seeing in Prod as well. Need to cover this issue ASAP.

**Comment by MushuEE** [comment]
Seems we are still hitting this, looks like bq got an update to be better with logging this error. Updating Prod to use new libs for better logging

**Comment by MushuEE** [comment]
Going to catch this and skip chunks where there is "too much data"

**Comment by spiffxp** [comment]
/sig testing
It's not clear to me whether we're still seeing this, did you notice this when trying restart kettle recently @BenTheElder ?

**Comment by BenTheElder** [comment]
There's a different more specific error message about the insert having a row that is too large. I have not seen this.
