### ISSUE TITLE
[approve plugin]panicking on removeFromStringSlice

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/test-infra#21677]
**What happened**:
The `approve` label was not added after `/approve` cmd had been issued.
https://github.com/openshift/release/pull/17387#issuecomment-814142909

**Anything else we need to know?**:
panic from Hook's log
```
panic caught: runtime error: slice bounds out of range [:7] with capacity 6. stack is: goroutine 399435 [running]:
runtime/debug.Stack(0xc02a0d1618, 0x1ecd9c0, 0xc02bf584e0)
	GOROOT/src/runtime/debug/stack.go:24 +0x9f
k8s.io/test-infra/prow/hook.errorOnPanic.func1(0xc02a0d3c40)
	prow/hook/events.go:451 +0x5b
panic(0x1ecd9c0, 0xc02bf584e0)
	GOROOT/src/runtime/panic.go:965 +0x1b9
k8s.io/test-infra/prow/plugins/approve/approvers.removeFromStringSlice(...)
	prow/plugins/approve/approvers/owners.go:205
k8s.io/test-infra/prow/plugins/approve/approvers.Owners.GetOwnersSet(0xc008a86000, 0x9, 0x10, 0xc008a860a0, 0x2, 0x6, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0x43eb, 0xc030125500, ...)
	prow/plugins/approve/approvers/owners.go:191 +0x2fe
k8s.io/test-infra/prow/plugins/approve/approvers.Owners.GetApprovers(0xc008a86000, 0x9, 0x10, 0xc008a86000, 0x9, 0x10, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0x43eb, 0xc030125500, ...)
	prow/plugins/approve/approvers/owners.go:77 +0x65
k8s.io/test-infra/prow/plugins/approve/approvers.Approvers.GetFilesApprovers(0xc008a86000, 0x9, 0x10, 0xc008a86000, 0x9, 0x10, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0x43eb, 0xc030125500, ...)
	prow/plugins/approve/approvers/owners.go:408 +0xb8
k8s.io/test-infra/prow/plugins/approve/approvers.Approvers.UnapprovedFiles(0xc008a86000, 0x9, 0x10, 0xc008a86000, 0x9, 0x10, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0x43eb, 0xc030125500, ...)
	prow/plugins/approve/approvers/owners.go:448 +0x98
k8s.io/test-infra/prow/plugins/approve/approvers.Approvers.AreFilesApproved(0xc008a86000, 0x9, 0x10, 0xc008a86000, 0x9, 0x10, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0x43eb, 0xc030125500, ...)
	prow/plugins/approve/approvers/owners.go:518 +0x78
k8s.io/test-infra/prow/plugins/approve/approvers.Approvers.RequirementsMet(0xc008a86000, 0x9, 0x10, 0xc008a86000, 0x9, 0x10, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0x43eb, 0xc030125500, ...)
	prow/plugins/approve/approvers/owners.go:528 +0x65
k8s.io/test-infra/prow/plugins/approve/approvers.Approvers.IsApproved(0xc008a86000, 0x9, 0x10, 0xc008a86000, 0x9, 0x10, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0x43eb, 0xc030125500, ...)
	prow/plugins/approve/approvers/owners.go:534 +0x5c
k8s.io/test-infra/prow/plugins/approve.handle(0xc030125500, 0x7f16c69043e8, 0xc037fcee10, 0x7f16c7f0b5a8, 0xc02e7b2fc0, 0xc013c1a048, 0x12, 0xc043f4f3b0, 0xc041153680, 0xc0178cc180, ...)
	prow/plugins/approve/approve.go:481 +0x24d8
k8s.io/test-infra/prow/plugins/approve.handleGenericComment(0xc030125500, 0x7f16c69043e8, 0xc037fcee10, 0x7f16c6904460, 0xc02c1185a0, 0xc013c1a048, 0x12, 0xc043f4f3b0, 0xc0005bf600, 0xc006d99578, ...)
	prow/plugins/approve/approve.go:194 +0x69c
k8s.io/test-infra/prow/plugins/approve.handleGenericCommentEvent(0x239bcb8, 0xc037fcee10, 0x237e4b8, 0xc023133860, 0x2394e88, 0xc02303c580, 0xc02317b080, 0x235c6e0, 0xc0194754b8, 0xc023133880, ...)
	prow/plugins/approve/approve.go:151 +0xf4
k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1.1(0xc5ca6098bf0d2602, 0xc034d05440)
	prow/hook/events.go:435 +0xf8
k8s.io/test-infra/prow/hook.errorOnPanic(0xc02cc4bd88, 0x0, 0x0)
	prow/hook/events.go:454 +0x5b
k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1(0xc0095e4fc0, 0xc030125340, 0xc02867f500, 0xc032538c37, 0x7, 0x20f2f18)
	prow/hook/events.go:435 +0x379
created by k8s.io/test-infra/prow/hook.(*Server).handleGenericComment
	prow/hook/events.go:425 +0x157
```

**Comment by hongkailiu** [comment]
Additional info.
I can approve other PRs in the same repo and I saw similar panicking logs for other users too.
