### ISSUE TITLE
./hack/update-labels.sh failing

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/test-infra#23421]
**What happened**:
When updating the label the `./hack/update-labels` script fails. I tried to search for different errors but failed to find anything that fixes it. There is a chance that this is a local environment issue, but I am unsure what could be wrong. I have been able to run this script successfully before to update a label in the past in the same environment setup except an older python version. 

**What you expected to happen**:
`labels.md` to be updated after updates to labels.yaml

**How to reproduce it (as minimally and precisely as possible)**:
Run `./hack/update-labels.sh`

Python 3.9, bazel 3.4.1 Mac OS Big Sur

**Please provide links to example occurrences, if any**:
Error details are below
```
pjoglekar@pjoglekar-a01 test-infra % ./hack/update-labels.sh  
update-all.sh*              update-deps.sh*             update-gofmt.sh*            update-protos.sh*
+ bazel run @io_k8s_test_infra//hack:update-labels
INFO: Repository py3_deps instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule pip_import defined at:
  /private/var/tmp/_bazel_pjoglekar/1fb424a846201af682defd2cbd21c8e2/external/rules_python/python/pip.bzl:44:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'py3_deps':
   pip_import failed: Collecting astroid==2.3.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ad/ae/86734823047962e7b8c8529186a1ac4a7ca19aaf1aa0c7713c022ef593fd/astroid-2.3.3-py3-none-any.whl
  Saved ./astroid-2.3.3-py3-none-any.whl
Collecting backports.functools_lru_cache==1.6.1 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/da/d1/080d2bb13773803648281a49e3918f65b31b7beebf009887a529357fd44a/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
  Saved ./backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
Collecting configparser==4.0.2 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
  Saved ./configparser-4.0.2-py2.py3-none-any.whl
Collecting influxdb==5.2.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ef/02/da676b46a3c7b7387151554bd71a15d455ec512222f7f5171ae8607522aa/influxdb-5.2.3-py2.py3-none-any.whl
  Saved ./influxdb-5.2.3-py2.py3-none-any.whl
Collecting isort==4.3.21 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
  Saved ./isort-4.3.21-py2.py3-none-any.whl
Collecting pylint==2.4.4 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/e9/59/43fc36c5ee316bb9aeb7cf5329cdbdca89e5749c34d5602753827c0aa2dc/pylint-2.4.4-py3-none-any.whl
  Saved ./pylint-2.4.4-py3-none-any.whl
Collecting parameterized==0.7.4 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/ba/6b/73dfed0ab5299070cf98451af50130989901f50de41fe85d605437a0210f/parameterized-0.7.4-py2.py3-none-any.whl
  Saved ./parameterized-0.7.4-py2.py3-none-any.whl
Collecting PyYAML==5.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz
Collecting ruamel.yaml==0.16.5 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl
  Saved ./ruamel.yaml-0.16.5-py2.py3-none-any.whl
Collecting setuptools==44.0.0 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl
  Saved ./setuptools-44.0.0-py2.py3-none-any.whl
Collecting sh==1.12.14 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
  Saved ./sh-1.12.14-py2.py3-none-any.whl
Collecting singledispatch==3.4.0.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
  Saved ./singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting wrapt==1.11.* (from astroid==2.3.3->-r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting six~=1.12 (from astroid==2.3.3->-r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
  Saved ./six-1.16.0-py2.py3-none-any.whl
Collecting lazy-object-proxy==1.4.* (from astroid==2.3.3->-r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/07/3f/a3d687f83c7d44970f70ff0400677746c8860b11f0c08f6b4e07205f0cdc/lazy-object-proxy-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/setup.py", line 61, in <module>
        setup(
      File "/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/tmpmqk9fv56/setuptools-tmp/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/tmpmqk9fv56/setuptools-tmp/setuptools/dist.py", line 336, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/tmpmqk9fv56/setuptools-tmp/setuptools/dist.py", line 470, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/.eggs/setuptools_scm-6.2.0-py3.9.egg/setuptools_scm/integration.py", line 29, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/.eggs/setuptools_scm-6.2.0-py3.9.egg/setuptools_scm/__init__.py", line 188, in _get_version
        dump_version(
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/.eggs/setuptools_scm-6.2.0-py3.9.egg/setuptools_scm/__init__.py", line 94, in dump_version
        version_fields = parsed_version.release
    AttributeError: 'SetuptoolsVersion' object has no attribute 'release'
    
    ----------------------------------------
 (Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/
)
ERROR: no such package '@py3_deps//': pip_import failed: Collecting astroid==2.3.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ad/ae/86734823047962e7b8c8529186a1ac4a7ca19aaf1aa0c7713c022ef593fd/astroid-2.3.3-py3-none-any.whl
  Saved ./astroid-2.3.3-py3-none-any.whl
Collecting backports.functools_lru_cache==1.6.1 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/da/d1/080d2bb13773803648281a49e3918f65b31b7beebf009887a529357fd44a/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
  Saved ./backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
Collecting configparser==4.0.2 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
  Saved ./configparser-4.0.2-py2.py3-none-any.whl
Collecting influxdb==5.2.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ef/02/da676b46a3c7b7387151554bd71a15d455ec512222f7f5171ae8607522aa/influxdb-5.2.3-py2.py3-none-any.whl
  Saved ./influxdb-5.2.3-py2.py3-none-any.whl
Collecting isort==4.3.21 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
  Saved ./isort-4.3.21-py2.py3-none-any.whl
Collecting pylint==2.4.4 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/e9/59/43fc36c5ee316bb9aeb7cf5329cdbdca89e5749c34d5602753827c0aa2dc/pylint-2.4.4-py3-none-any.whl
  Saved ./pylint-2.4.4-py3-none-any.whl
Collecting parameterized==0.7.4 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/ba/6b/73dfed0ab5299070cf98451af50130989901f50de41fe85d605437a0210f/parameterized-0.7.4-py2.py3-none-any.whl
  Saved ./parameterized-0.7.4-py2.py3-none-any.whl
Collecting PyYAML==5.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz
Collecting ruamel.yaml==0.16.5 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl
  Saved ./ruamel.yaml-0.16.5-py2.py3-none-any.whl
Collecting setuptools==44.0.0 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl
  Saved ./setuptools-44.0.0-py2.py3-none-any.whl
Collecting sh==1.12.14 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
  Saved ./sh-1.12.14-py2.py3-none-any.whl
Collecting singledispatch==3.4.0.3 (from -r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
  Saved ./singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting wrapt==1.11.* (from astroid==2.3.3->-r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting six~=1.12 (from astroid==2.3.3->-r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
  Saved ./six-1.16.0-py2.py3-none-any.whl
Collecting lazy-object-proxy==1.4.* (from astroid==2.3.3->-r /Users/pjoglekar/github-forked/test-infra/requirements3.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/07/3f/a3d687f83c7d44970f70ff0400677746c8860b11f0c08f6b4e07205f0cdc/lazy-object-proxy-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/setup.py", line 61, in <module>
        setup(
      File "/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/tmpmqk9fv56/setuptools-tmp/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/tmpmqk9fv56/setuptools-tmp/setuptools/dist.py", line 336, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/tmpmqk9fv56/setuptools-tmp/setuptools/dist.py", line 470, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/.eggs/setuptools_scm-6.2.0-py3.9.egg/setuptools_scm/integration.py", line 29, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/.eggs/setuptools_scm-6.2.0-py3.9.egg/setuptools_scm/__init__.py", line 188, in _get_version
        dump_version(
      File "/private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/.eggs/setuptools_scm-6.2.0-py3.9.egg/setuptools_scm/__init__.py", line 94, in dump_version
        version_fields = parsed_version.release
    AttributeError: 'SetuptoolsVersion' object has no attribute 'release'
    
    ----------------------------------------
 (Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/q0/_4rbvk4d4sl6l3_bp40jvh080000gr/T/pip-build-vufh_4zz/lazy-object-proxy/
)
INFO: Elapsed time: 5.153s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```
**Anything else we need to know?**:

**Comment by spiffxp** [comment]
IIRC bazel is not the best at being hermetic with python

Do you get the same error if you `pip3 install -r requirements3.txt`?

**Comment by spiffxp** [comment]
FWIW I don't see this error, and my env is similar
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.5.1
BuildVersion:	20G80
$ python --version
Python 3.9.6
$ bazel --version
bazel 3.4.1
```

**Comment by PushkarJ** [comment]
This seems like a local issue as I ran it today and it worked without any change in my environment.
