### ISSUE TITLE
Kettle-Staging volume is full

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#23459]
**What happened**:
`kettle-staging` deployment cannot run due to 
```
Traceback (most recent call last):
  File "make_db.py", line 376, in <module>
    OPTIONS.buildlimit,
  File "make_db.py", line 330, in main
    threads, client_class, build_limit)
  File "make_db.py", line 269, in get_all_builds
    db.insert_build(build_dir, started, finished)
  File "/kettle/model.py", line 87, in insert_build
    finished and finished.get('timestamp', None))).lastrowid
sqlite3.OperationalError: database or disk is full
Command exited with non-zero status 1
2.90user 2.10system 0:03.83elapsed 130%CPU (0avgtext+0avgdata 172584maxresident)k
0inputs+64outputs (0major+131989minor)pagefaults 0swaps
+ time python3 make_db.py --buckets buckets.yaml --junit --threads 32
Traceback (most recent call last):
  File "/kettle/update.py", line 87, in <module>
    main()
  File "/kettle/update.py", line 50, in main
    call(f'time python3 make_db.py --buckets buckets.yaml --junit --threads {THREADS}')
  File "/kettle/update.py", line 44, in call
    raise OSError('invocation failed')
OSError: invocation failed
```

The volume is 
```
      - name: data
        persistentVolumeClaim:
          claimName: kettle-data-staging
```

Defined in [pv-staging.yaml](https://github.com/kubernetes/test-infra/blob/master/kettle/pv-staging.yaml)

Accessed here: https://console.cloud.google.com/kubernetes/persistentvolumeclaim/us-west1-b/g8r/default/kettle-data-staging/details?project=k8s-gubernator

/area Kettle
/type cleanup

**Comment by MushuEE** [comment]
Increased claim size to match Prod 1000GB 

https://console.cloud.google.com/compute/disksDetail/zones/us-west1-b/disks/kettle-data-staging?folder=&organizationId=&project=k8s-gubernator

Will make CL to update docs

**Comment by MushuEE** [comment]
Fixed by cleaning the data/ and clearing the staging database.
