### ISSUE TITLE
Turn to use Python3 as bazel default python interpreter

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/test-infra#23975]
**What would you like to be added**:
When we run `./hack/update-bazel.sh`, it should build successfully, even only python3 installation available.

**Why is this needed**:
I found it would panic if no python2 installation found:

```
INFO: Repository pip_deps instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule pip_import defined at:
  /private/var/tmp/_bazel_user/eb2106dd05673888d179bfdf510c291b/external/rules_python/python/pip.bzl:44:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_deps':
   pip_import failed:  (Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/var/tmp/_bazel_user/eb2106dd05673888d179bfdf510c291b/external/rules_python/tools/piptool.par/__main__.py", line 66, in <module>
  File "/private/var/tmp/_bazel_user/eb2106dd05673888d179bfdf510c291b/external/rules_python/tools/piptool.par/__main__.py", line 45, in extract_packages
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1286, in set_extraction_path
    "Can't change extraction path, files already extracted"
ValueError: Can't change extraction path, files already extracted
)
ERROR: no such package '@pip_deps//': pip_import failed:  (Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/var/tmp/_bazel_user/eb2106dd05673888d179bfdf510c291b/external/rules_python/tools/piptool.par/__main__.py", line 66, in <module>
  File "/private/var/tmp/_bazel_user/eb2106dd05673888d179bfdf510c291b/external/rules_python/tools/piptool.par/__main__.py", line 45, in extract_packages
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1286, in set_extraction_path
    "Can't change extraction path, files already extracted"
ValueError: Can't change extraction path, files already extracted
)
INFO: Elapsed time: 1.187s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Since Python27 has been retired at 2020.01.01, we need to update this requirement to python3.

**Comment by BenTheElder** [comment]
we no longer use bazel #23830
