### ISSUE TITLE
[help] raise ```Error: Missing or insufficient permissions. ``` when using gubernator

### ISSUE THREAD

**Issue by hawkingrei** [kubernetes/test-infra#24986]
**What happened**:

I succeed to deploy gubernator on the app engine. but when I visit it, it raises the error messenger.

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~myclass2004/v20220124.441045022889207234/view_base.py", line 78, in dispatch
    sessions_config['secret_key'] = get_session_secret()
  File "/base/data/home/apps/s~myclass2004/v20220124.441045022889207234/view_base.py", line 44, in get_session_secret
    return str(secrets.get('session'))
  File "/base/data/home/apps/s~myclass2004/v20220124.441045022889207234/secrets.py", line 47, in get
    data = Secret.make_key(key, per_host).get()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/ext/ndb/key.py", line 572, in get
    return self.get_async(**ctx_options).get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 760, in get
    entity = yield self._get_batcher.add_once(key, options)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 345, in _get_tasklet
    entities = yield self._conn.async_get(options, datastore_keys)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 513, in _on_rpc_completion
    result = rpc.get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 615, in get_result
    return self.__get_result_hook(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1654, in __get_hook
    self.check_rpc_success(rpc)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/676f3dbea5eddbaf/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1377, in check_rpc_success
    raise _ToDatastoreError(err)
Error: Missing or insufficient permissions.
```

I have changed the access to the app engine default account. now it is the owner. but it still raises the error messanger.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
FWIW: gubernator is essentially deprecated. I'm sorry but I don't think anyone has bandwidth to support this.

In current usage, we use https://prow.k8s.io which is the `deck` subcommand of `prow/` in this repo.
