### ISSUE TITLE
FindIssues() method of Github client does not work when app_auth is enabled

### ISSUE THREAD

**Issue by oliver-goetz** [kubernetes/test-infra#25066]
**What happened**:
Calling [FindIssues()](https://github.com/kubernetes/test-infra/blob/1a76bd66eda42678652dee90563e7fc02539e8a3/prow/github/client.go#L3463) method from an external-plugin which is using app auth results in an exception.

```json
{
  "component": "unset",
  "error": "error searching for issues matching commit: Get \"http://ghproxy/search/issues?per_page=100&q=c59aaaf1366252ac1acc72c8f9588c67059f1e56+org%3Agardener+repo%3Agardener%2Fci-infra+type%3Apr+state%3Aopen\": BUG apps auth requested but empty org, please report this to the test-infra repo. Stack: goroutine 122 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\nk8s.io/test-infra/prow/github.(*appsRoundTripper).addAppInstallationAuth(0xc0761b21f9e9e42e, 0xc0000fa700)\n\t/code/vendor/k8s.io/test-infra/prow/github/app_auth_roundtripper.go:127 +0xae\nk8s.io/test-infra/prow/github.(*appsRoundTripper).RoundTrip(0xc000734240, 0xc0000fa700)\n\t/code/vendor/k8s.io/test-infra/prow/github/app_auth_roundtripper.go:74 +0x85\nnet/http.send(0xc0000fa600, {0x1ec8ca0, 0xc000734240}, {0x1b6f8e0, 0x4bea01, 0x2d6a180})\n\t/usr/local/go/src/net/http/client.go:252 +0x5d8\nnet/http.(*Client).send(0xc0007266c0, 0xc0000fa600, {0xc000742d20, 0x30, 0x2d6a180})\n\t/usr/local/go/src/net/http/client.go:176 +0x9b\nnet/http.(*Client).do(0xc0007266c0, 0xc0000fa600)\n\t/usr/local/go/src/net/http/client.go:725 +0x908\nnet/http.(*Client).Do(0xc000742070, 0xc000666790)\n\t/usr/local/go/src/net/http/client.go:593 +0x19\nk8s.io/test-infra/prow/github.(*client).doRequest(0xc000726900, {0x1ef7f30, 0xc000128000}, {0x1bd0589, 0x0}, {0xc0000dc960, 0x0}, {0x0, 0x0}, {0x0, ...}, ...)\n\t/code/vendor/k8s.io/test-infra/prow/github/client.go:1174 +0xa1d\nk8s.io/test-infra/prow/github.(*client).requestRetryWithContext(0xc000726900, {0x1ef7f30, 0xc000128000}, {0x1bd0589, 0x3}, {0xc0000da1b0, 0x87}, {0x0, 0x0}, {0x0, ...}, ...)\n\t/code/vendor/k8s.io/test-infra/prow/github/client.go:1035 +0x267\nk8s.io/test-infra/prow/github.(*client).readPaginatedResultsWithValuesWithContext(0x0, {0x1ef7f30, 0xc000128000}, {0xc000466fa0, 0xe}, 0x4e26e5, {0x0, 0x0}, {0x0, 0x0}, ...)\n\t/code/vendor/k8s.io/test-infra/prow/github/client.go:1965 +0x187\nk8s.io/test-infra/prow/github.(*client).readPaginatedResultsWithValues(...)\n\t/code/vendor/k8s.io/test-infra/prow/github/client.go:1956\nk8s.io/test-infra/prow/github.(*client).FindIssues(0x1c0d08e, {0xc00054a480, 0x5f}, {0x0, 0x0}, 0x0)\n\t/code/vendor/k8s.io/test-infra/prow/github/client.go:3459 +0x425\nmain.(*claAssistantPlugin).handleStatusEvent.func1()\n\t/code/prow/external-plugins/cla-assistant/plugin.go:147 +0x170\ngithub.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc000667bc0, {0x1edfa88, 0xc0000a0360}, 0x0, {0x0, 0x0})\n\t/code/vendor/github.com/cenkalti/backoff/v4/retry.go:55 +0x12a\ngithub.com/cenkalti/backoff/v4.RetryNotify(...)\n\t/code/vendor/github.com/cenkalti/backoff/v4/retry.go:34\ngithub.com/cenkalti/backoff/v4.Retry(...)\n\t/code/vendor/github.com/cenkalti/backoff/v4/retry.go:28\nmain.(*claAssistantPlugin).handleStatusEvent(0xc000468420, 0x0, 0xc0006ac500)\n\t/code/prow/external-plugins/cla-assistant/plugin.go:145 +0x30e\nmain.(*httpServer).handleEvent.func3()\n\t/code/prow/external-plugins/cla-assistant/server.go:87 +0x55\ncreated by main.(*httpServer).handleEvent\n\t/code/prow/external-plugins/cla-assistant/server.go:86 +0x338\n",
  "event-GUID": "7074a2f0-82a3-11ec-90dc-ba28b2f6d9b8",
  "event-type": "status",
  "file": "/code/prow/external-plugins/cla-assistant/server.go:88",
  "func": "main.(*httpServer).handleEvent.func3",
  "level": "info",
  "msg": "Error handling event.",
  "plugin": "cla-assistant",
  "severity": "info",
  "time": "2022-01-31T14:39:11Z"
}
```

**What you expected to happen**:
Finding issues

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
The challenge here is that each requests needs to be attributed to a GH organization, which does two things:
* Use that organizations token budget
* Use the permissions this app has in that organization

And in the case of a search request, it isn't obvious how to derive the right organization from the request. The best I can think of is to try to find one in the query and just use the first or a random one if there is more than one. Alternatively, we could add an explicit `FindIssuesWithOrg` and the caller passes the org. This would work fell for hook plugins.

@oliver-goetz Your usecase is a hook plugin, right? WDYT about a new method in the GH client that gets the org as explicit arg  (You can get the org from the event)?

**Comment by oliver-goetz** [comment]
yes, that sound good.
I'm using a GraphQL instead at the moment. It is built in my case now, but `FindIssuesWithOrg` sounds like a useful method. `FindIssues` is the only method of IssueClient which is not working with app auth. I never used GraphQL before, so it took a minute or two to make it work.

**Comment by alvaroaleman** [comment]
Right, the problem you have with graphql is that the responses you get from
there can not be cached, which in turn means it uses up a lot of api quota,
which depending on the activity in your Prow setup might or might not be a
problem

**Comment by oliver-goetz** [comment]
Understood.
It does not look complicated, I can give it a try next week
