### ISSUE TITLE
kettle out of disk for sqlite3 db

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#25162]
**What happened**:

Received email alert with:

`New error in k8s-gubernator gke_instances`:
```
sqlite3.OperationalError
database or disk is full
Traceback (most recent call last): File "make_db.py", line 376, in OPTIONS.buildlimit, File "make_db.py", line 336, in main download_junit(db, threads, client_class) File "make_db.py", line 318, in download_junit db.insert_build_junits(build_id, junits) File "/kettle/model.py", line 110, in insert_build_junits (path, memoryview(zlib.compress(data.encode('utf-8'), 9)))) sqlite3.OperationalError: database or disk is full
```

**What you expected to happen**:

not out of disk

**How to reproduce it (as minimally and precisely as possible)**:

run kettle for years

**Please provide links to example occurrences, if any**:

??

**Anything else we need to know?**:

thread in testing-ops:
https://kubernetes.slack.com/archives/C7J9RP96G/p1644346402826379

/area kettle
/assign

**Comment by BenTheElder** [comment]
I think this is only in the staging instance, bumping disks anyhow as we are not that far from the limits.
