### ISSUE TITLE
[Kettle]: Permission denied when trying to attach to PubSub subscription. 

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#25879]
**What happened**:
> kubectl logs -f kettle-cc9cbb879-bd44q
The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "stream.py", line 351, in <module>
    stop=StopWhen(OPTIONS.stop_at))
  File "stream.py", line 182, in main
    results = retry(subscriber.pull, subscription=subscription_path, max_messages=1000)
  File "stream.py", line 106, in retry
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/usr/local/lib/python3.6/dist-packages/google/pubsub_v1/services/subscriber/client.py", line 1103, in pull
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.PermissionDenied: 403 User not authorized to perform this action.
```
**What you expected to happen**:
Kettle to have permissions.

**How to reproduce it (as minimally and precisely as possible)**:
View logs as above.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by MushuEE** [comment]
It looks like kettle's account is no longer added as editor to the subscription? 
/sig testing

**Comment by MushuEE** [comment]
```
gcloud pubsub subscriptions add-iam-policy-binding \
                                                    projects/kubernetes-jenkins/subscriptions/kettle-filtered \
                                                    --member=serviceAccount:kettle@k8s-gubernator.iam.gserviceaccount.com \
                                                    --role=roles/pubsub.editor
```
