### ISSUE TITLE
fuzz job failing continuously

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#26113]
https://testgrid.k8s.io/sig-testing-misc#test-infra-fuzz

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/test-infra-fuzz/1519343880913293312

```
INFO: 63 Extra Counters
INFO:        2 files found in /logs/artifacts/cifuzz-corpus/fuzzer
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 2 min: 1b max: 2b total: 3b rss: 43Mb
#3	INITED ft: 5 corp: 2/3b exec/s: 0 rss: 43Mb
panic: runtime error: index out of range [10000] with length 0
goroutine 17 [running, locked to thread]:
k8s.io/test-infra/experiment/cifuzz_test.Fuzz(...)
	k8s.io/test-infra/experiment/cifuzz_test/fuzz.go:25
main.LLVMFuzzerTestOneInput(...)
	./main.362733635.go:21
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1663==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000067f (pc 0x0000005b0bc1 bp 0x10c00005ac80 sp 0x10c00005ac68 T0)
SCARINESS: 10 (signal)
    #0 0x5b0bc1 in runtime.raise.abi0 runtime/sys_linux_amd64.s:165
```

/kind failing-test

cc @mpherman2

**Comment by BenTheElder** [comment]
see also:
https://testgrid.k8s.io/sig-testing-misc#test-infra-cfl-coverage-report

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/26398
