### ISSUE TITLE
Submit queue is crash looping

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2630]
```
I0502 15:18:14.206542       1 mungers.go:93] Initialized munger: submit-queue
I0502 15:18:22.337242       1 utils.go:192] Got a non-success response 404 while reading data for ci-kubernetes-e2e-gci-gce-kubenet/latest-build.txt
E0502 15:18:22.845248       1 utils.go:249] Got a non-success response 404 while reading data for ci-kubernetes-e2e-gci-gce-kubenet/-1/finished.json
W0502 15:18:23.180125       1 bucket.go:130] No matching files were found (from: https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o?prefix=logs%2Fci-kubernetes-e2e-gci-gce-kubenet%2F-1%2Fartifacts%2Fjunit)
I0502 15:18:32.283990       1 mungers.go:92] {}

I0502 15:18:32.285174       1 mungers.go:93] Initialized munger: issue-cacher
F0502 15:18:32.287734       1 mungegithub.go:118] unable to initialize mungers: line 983, column 0: wrong number of fields in line
goroutine 1 [running]:
k8s.io/test-infra/vendor/github.com/golang/glog.stacks(0xf4ae00, 0x0, 0x0, 0x0)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/vendor/github.com/golang/glog/glog.go:766 +0xb8
k8s.io/test-infra/vendor/github.com/golang/glog.(*loggingT).output(0xf2ebe0, 0xc800000003, 0xc8200ae480, 0xf0b645, 0xe, 0x76, 0x0)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/vendor/github.com/golang/glog/glog.go:717 +0x259
k8s.io/test-infra/vendor/github.com/golang/glog.(*loggingT).printf(0xf2ebe0, 0xc800000003, 0xc5f1e0, 0x20, 0xc8200c5b10, 0x1, 0x1)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/vendor/github.com/golang/glog/glog.go:655 +0x1d4
k8s.io/test-infra/vendor/github.com/golang/glog.Fatalf(0xc5f1e0, 0x20, 0xc8200c5b10, 0x1, 0x1)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/vendor/github.com/golang/glog/glog.go:1145 +0x5d
main.main.func1(0xc8200b7200, 0xc82000b600, 0x0, 0x2a, 0x0, 0x0)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/mungegithub/mungegithub.go:118 +0x522
k8s.io/test-infra/vendor/github.com/spf13/cobra.(*Command).execute(0xc8200b7200, 0xc82000a2d0, 0x2a, 0x2b, 0x0, 0x0)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/vendor/github.com/spf13/cobra/command.go:561 +0x62c
k8s.io/test-infra/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8200b7200, 0xc8200b7200, 0x0, 0x0)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/vendor/github.com/spf13/cobra/command.go:651 +0x55c
k8s.io/test-infra/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200b7200, 0x0, 0x0)
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/vendor/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
	/usr/local/google/home/grod/work/src/k8s.io/test-infra/mungegithub/mungegithub.go:141 +0x395
```

I suspect one of these is having trouble: `issue-cacher,flake-manager,old-test-getter`

**Comment by fejta** [comment]
I bet the problem is here: https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/flake-manager.go#L110

**Comment by fejta** [comment]
Woo!

https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.csv
```
We can make this file beautiful and searchable if this error is corrected: It looks like row 983 should actually have 4 columns, instead of 3.
```

**Comment by fejta** [comment]
I'm going to make the submit queue robust to this problem. We should be able to start the SQ even if the csv is malformed
