### ISSUE TITLE
Support running node e2e tests from prow

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#2632]
I followed the instructions on https://github.com/kubernetes/test-infra/blob/master/experiment/pod.yaml to run `ci-kubernetes-node-kubelet` from prow using the following configuration.

```
apiVersion: v1
kind: Pod
metadata:
  name: k8s-e2e
spec:
  containers:
  - name: k8s-e2e-test
    image: gcr.io/k8s-testimages/kubekins-e2e-prow:v20170418-c08e1094
    args:
    - "--timeout=60"
    - "--repo=k8s.io/kubernetes=master"
    env:
      - name: JOB_NAME
        value: ci-kubernetes-node-kubelet
      - name: PROJECT
        value: ygg-gke-dev
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: JENKINS_GCE_SSH_PRIVATE_KEY_FILE
        value: /etc/ssh-key-secret/ssh-private
      - name: JENKINS_GCE_SSH_PUBLIC_KEY_FILE
        value: /etc/ssh-key-secret/ssh-public       
      - name: USER
        value: prow
    volumeMounts:
    - mountPath: /etc/service-account
      name: service
      readOnly: true
    - mountPath: /etc/ssh-key-secret
      name: ssh
      readOnly: true
  volumes:
  - name: service
    secret:
      secretName: "service-account"
      defaultMode: 0400
  - name: ssh
    secret:
      secretName: "ssh-key-secret"
      defaultMode: 0400
```

The job failed with the following error.

```
W0502 05:51:49.351] Run: ('docker', 'pull', 'gcr.io/k8s-testimages/kubekins-node:1.7-latest')
W0502 05:51:49.406] Cannot connect to the Docker daemon. Is the docker daemon running on this host?
W0502 05:51:49.407] Traceback (most recent call last):
W0502 05:51:49.407]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_kubelet.py", line 129, in <module>
W0502 05:51:49.408]     ARGS.service_account,
W0502 05:51:49.408]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_kubelet.py", line 76, in main
W0502 05:51:49.408]     check('docker', 'pull', img)  # Update image if changed
W0502 05:51:49.409]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_kubelet.py", line 45, in check
W0502 05:51:49.409]     subprocess.check_call(cmd)
W0502 05:51:49.409]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0502 05:51:49.409]     raise CalledProcessError(retcode, cmd)
W0502 05:51:49.410] subprocess.CalledProcessError: Command '('docker', 'pull', 'gcr.io/k8s-testimages/kubekins-node:1.7-latest')' returned non-zero exit status 1
E0502 05:51:49.412] Build failed
I0502 05:51:49.412] process 261 exited with code 1 after 0.0m
E0502 05:51:49.412] FAIL: ci-kubernetes-node-kubelet
```

This is because `kubernetes_kubelet.py` scenario does not support local mode. See https://github.com/kubernetes/test-infra/pull/2622 for more context.

**Comment by yguo0905** [comment]
@krzyzacy
@fejta
@ixdy

**Comment by krzyzacy** [comment]
/close
this is done
