### ISSUE TITLE
Tide panics with `invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by timebertt** [kubernetes/test-infra#27046]
**What happened**:

After an upgrade from `gcr.io/k8s-prow/tide:v20220803-65793402b8` to `gcr.io/k8s-prow/tide:v20220805-b020793770` (https://github.com/gardener/ci-infra/pull/336), `tide` is in `CrashLoopBackOff` and panicking with:
```
...
{"component":"tide","controller":"status-update","file":"k8s.io/test-infra/prow/tide/status.go:681","func":"k8s.io/test-infra/prow/tide.(*statusController).search.func1.1","latestPR":"2022-08-05T11:08:23Z","level":"debug","msg":"Advanced start time","query":"is:pr state:open sort:updated-asc archived:false  repo:\"gardener/ci-infra\" repo:\"gardener/gardener\"","severity":"debug","time":"2022-08-05T11:12:03Z"}
{"component":"tide","controller":"status-update","duration":"1.780608269s","file":"k8s.io/test-infra/prow/tide/status.go:608","func":"k8s.io/test-infra/prow/tide.(*statusController).sync.func1","level":"info","msg":"Statuses synced.","severity":"info","time":"2022-08-05T11:12:03Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x718d89]

goroutine 263 [running]:
github.com/sirupsen/logrus.(*Entry).WithFields(0x1d7bba0?, 0xc0034dea28?)
	github.com/sirupsen/logrus@v1.8.1/entry.go:126 +0x29
github.com/sirupsen/logrus.(*Entry).WithField(...)
	github.com/sirupsen/logrus@v1.8.1/entry.go:121
k8s.io/test-infra/prow/tide.checkRunNodesToContexts(0x0?, {0xc0034d4600?, 0x5?, 0x0?})
	k8s.io/test-infra/prow/tide/tide.go:2317 +0x150
k8s.io/test-infra/prow/tide.(*GitHubProvider).headContexts(0xc000849560, 0xc0034dfc70)
	k8s.io/test-infra/prow/tide/tide.go:2150 +0xa73
k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1(0xc001a2fc70)
	k8s.io/test-infra/prow/tide/status.go:417 +0x465
k8s.io/test-infra/prow/tide.(*statusController).setStatuses(0xc000120bb0, {0xc000851800, 0x7, 0xc000b35040?}, 0xc00342d770, {0x0?, 0x0?}, 0xc00342d7a0, 0xc00342d7d0)
	k8s.io/test-infra/prow/tide/status.go:475 +0x353
k8s.io/test-infra/prow/tide.(*statusController).sync(0xc000120bb0, 0xc0007a0f18?, {0x0?, 0x0?}, 0xc000074c00?, 0xc000424101?)
	k8s.io/test-infra/prow/tide/status.go:613 +0xfb
k8s.io/test-infra/prow/tide.(*statusController).waitSync(0xc000120bb0)
	k8s.io/test-infra/prow/tide/status.go:594 +0x1e7
k8s.io/test-infra/prow/tide.(*statusController).run(0xc000120bb0)
	k8s.io/test-infra/prow/tide/status.go:570 +0xd1
created by k8s.io/test-infra/prow/tide.NewController
	k8s.io/test-infra/prow/tide/tide.go:361 +0x3e5
```

**What you expected to happen**:

`tide` not to panic.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I rolled back to the old image and it worked fine. Upgrading again immediately causes the same panic.

/sig testing

**Comment by smg247** [comment]
We saw this in OpenShift too. Potentially caused by: https://github.com/kubernetes/test-infra/pull/26597?

**Comment by chaodaiG** [comment]
ack, reverting
