### ISSUE TITLE
//verify:verify-pylint is not fully hermetic

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2713]
Apparently I don't have pylint + necessary dependencies installed on my system:
```
==================== Test output for //verify:verify-pylint:
Traceback (most recent call last):
  File ".../bazel-sandbox/4a5cc76d-8528-4a8f-be2e-05b525942fda-0/execroot/test-infra/bazel-out/local-fastbuild/bin/verify/verify-pylint.runfiles/__main__/../pylint/__main__.py", line 8, in <module>
    pylint.run_pylint()
  File ".../bazel-sandbox/4a5cc76d-8528-4a8f-be2e-05b525942fda-0/execroot/test-infra/bazel-out/local-fastbuild/bin/verify/verify-pylint.runfiles/pylint/__init__.py", line 12, in run_pylint
    from pylint.lint import Run
  File ".../bazel-sandbox/4a5cc76d-8528-4a8f-be2e-05b525942fda-0/execroot/test-infra/bazel-out/local-fastbuild/bin/verify/verify-pylint.runfiles/pylint/lint.py", line 34, in <module>
    import astroid
ImportError: No module named astroid
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
================================================================================
```

**Comment by krzyzacy** [comment]
and you'd better have the same pylint settings as in the repo :-)

**Comment by spxtr** [comment]
Ah, I didn't make sure all of pylint's deps were installed in the workspace, just pylint itself.

**Comment by BenTheElder** [comment]
Yep, this has still been pretty annoying.
/assign
I want to see this fixed at some point. I look forward to `bazel test //...` passing 100% locally.

**Comment by BenTheElder** [comment]
Grrrr https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4821/pull-test-infra-bazel/8171/

**Comment by BenTheElder** [comment]
closing in favor of up to date issue https://github.com/kubernetes/test-infra/issues/4849
