### ISSUE TITLE
Bazel missing dependencies

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#2878]
Some tests are failing when I run `bazel test //...`. Specifically, `//kettle:make_db_test`, `//kettle:make_json_test`, `//kettle:model_test`, and `//triage:script_test`
The kettle failures are all caused by missing the `_sqlite3` module and the triage failure is caused by missing a `mocha` module.

Kettle failure example:
```
Traceback (most recent call last):
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/1852ce316a6d20f369402a4c3ea6bced/bazel-sandbox/2194457009083489923/execroot/test-infra/bazel-out/local-fastbuild/bin/kettle/model_test.runfiles/__main__/kettle/model_test.py", line 19, in <module>
    import model
  File "/usr/local/google/home/colew/go/src/k8s.io/test-infra/kettle/model.py", line 19, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7.13/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7.13/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

Triage failure:

```
module.js:457
    throw err;
    ^

Error: Cannot find module '/local/google/home/colew/.cache/bazel/_bazel_colew/1852ce316a6d20f369402a4c3ea6bced/external/npm_mocha/bin/mocha'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.```

**Comment by ixdy** [comment]
The triage test will be fixed by #2877.

**Comment by cjwagner** [comment]
Bazel is also missing the module `six` which is required by pylint:
```
Traceback (most recent call last):
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/1852ce316a6d20f369402a4c3ea6bced/bazel-sandbox/8285980471610289467/execroot/test-infra/bazel-out/local-fastbuild/bin/verify/verify-pylint.runfiles/__main__/../pylint/__main__.py", line 8, in <module>
    pylint.run_pylint()
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/1852ce316a6d20f369402a4c3ea6bced/bazel-sandbox/8285980471610289467/execroot/test-infra/bazel-out/local-fastbuild/bin/verify/verify-pylint.runfiles/pylint/__init__.py", line 12, in run_pylint
    from pylint.lint import Run
  File "/usr/local/google/home/colew/.cache/bazel/_bazel_colew/1852ce316a6d20f369402a4c3ea6bced/bazel-sandbox/8285980471610289467/execroot/test-infra/bazel-out/local-fastbuild/bin/verify/verify-pylint.runfiles/pylint/lint.py", line 32, in <module>
    import six
ImportError: No module named six
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
```

**Comment by BenTheElder** [comment]
Noting that I ran into this recently when working on #4169. We still have some python deps that aren't handled by bazel. https://github.com/kubernetes/test-infra/pull/4169/files#diff-1ac0b76096c24dc7d37ac127538887d7R37

**Comment by BenTheElder** [comment]
/assign
Not sure when/if I will get this fixed, but I think now it's just some of the python dependencies currently.
xref: https://github.com/kubernetes/test-infra/issues/2713

**Comment by BenTheElder** [comment]
These specific complaints were fixed but the title is still an issue, it should now just be python deps which I have over at https://github.com/kubernetes/test-infra/issues/4849.
