### ISSUE TITLE
triage tests broken at head

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2901]
```
bash$ bazel test //... --test_output=streamed
INFO: Found 369 targets and 57 test targets...
module.js:457
    throw err;
    ^

Error: Cannot find module '/local/google/home/fejta/.cache/bazel/_bazel_fejta/99e1f84903a85a59ec79394ca2594688/external/npm_mocha/bin/mocha'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
FAIL: //triage:script_test
//triage:script_test                                                     FAILED in 0.1s
```

/assign @rmmh

**Comment by rmmh** [comment]
worksforme

**Comment by rmmh** [comment]
I think @ixdy had a PR out to fix this

**Comment by fejta** [comment]
Oh I might be on an old commit
/unassign @rmmh 
/assign

**Comment by ixdy** [comment]
yes, please sync to head and see if it's still broken.
