### ISSUE TITLE
TestInterrupts deadlocks

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#29104]
The test is flaky https://storage.googleapis.com/k8s-triage/index.html?date=2023-01-17&pr=1&test=TestInterrupts

and it is easy to repro the deadlock running it multiple times with the flag `-count 10`, not need to use the `stress`tool

```
go test -timeout 30s -run ^TestInterrupts$ k8s.io/test-infra/prow/interrupts -count 10
time="2023-03-21T18:37:42Z" level=info msg="Received signal." signal=hangup
time="2023-03-21T18:37:42Z" level=info msg="Interrupt received."
time="2023-03-21T18:37:42Z" level=info msg="Server shutting down..."
time="2023-03-21T18:37:42Z" level=info msg="Server shutting down..."
time="2023-03-21T18:37:42Z" level=info msg="Server exited." error="http: Server closed"
time="2023-03-21T18:37:42Z" level=info msg="Worker shutting down..."
time="2023-03-21T18:37:42Z" level=info msg="Server exited." error="http: Server closed"
time="2023-03-21T18:37:42Z" level=info msg="All workers gracefully terminated, exiting."
time="2023-03-21T18:37:42Z" level=info msg="Server shutting down..."
time="2023-03-21T18:37:42Z" level=info msg="Server exited." error="http: Server closed"
time="2023-03-21T18:37:43Z" level=info msg="Server shutting down..."
time="2023-03-21T18:37:43Z" level=info msg="Server exited." error="http: Server closed"
time="2023-03-21T18:37:43Z" level=info msg="Worker shutting down..."
time="2023-03-21T18:37:43Z" level=info msg="Interrupt received."
time="2023-03-21T18:37:43Z" level=info msg="All workers gracefully terminated, exiting."
--- FAIL: TestInterrupts (0.38s)
    interrupts_test.go:111: could not reach server registered with ListenAndServe(): Get "http://127.0.0.1:34981": dial tcp 127.0.0.1:34981: connect: connection refused
    interrupts_test.go:142: could not reach server registered with ListenAndServeTLS(): Get "https://127.0.0.1:45463": dial tcp 127.0.0.1:45463: connect: connection refused
    interrupts_test.go:208: server registered with ListenAndServe() was not serving
    interrupts_test.go:214: server registered with ListenAndServeTLS() was not serving
    interrupts_test.go:220: work registered with Tick() was called 0 times, not 2; interval was requested 1 times
time="2023-03-21T18:37:43Z" level=info msg="Server shutting down..."
time="2023-03-21T18:37:43Z" level=info msg="Server exited." error="http: Server closed"
time="2023-03-21T18:37:43Z" level=info msg="Server shutting down..."
time="2023-03-21T18:37:43Z" level=info msg="Server exited." error="http: Server closed"
time="2023-03-21T18:37:43Z" level=info msg="Worker shutting down..."
time="2023-03-21T18:37:43Z" level=info msg="Interrupt received."
time="2023-03-21T18:37:43Z" level=info msg="All workers gracefully terminated, exiting."
panic: test timed out after 30s
running tests:
        TestInterrupts (29s)

goroutine 138 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:2241 +0x3b9
created by time.goFunc
        /usr/local/google/home/aojea/sdk/go1.20.1/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000502ea0, {0x75e62b?, 0x4e2ac5?}, 0x78ee48)
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0xc0000acc00?)
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc000502ea0, 0xc000193c88)
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0000f8960?, {0x9b57e0, 0x1, 0x1}, {0x7fc521f4bf48?, 0x17fc521f40108?, 0x9c2960?})
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0000f8960)
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:1906 +0x63a
main.main()
        _testmain.go:47 +0x1aa

goroutine 95 [chan send]:
k8s.io/test-infra/prow/interrupts.TestInterrupts(0xc000503040)
        /usr/local/google/home/aojea/src/test-infra/prow/interrupts/interrupts_test.go:193 +0xb8f
testing.tRunner(0xc000503040, 0x78ee48)
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/google/home/aojea/sdk/go1.20.1/src/testing/testing.go:1629 +0x3ea
FAIL    k8s.io/test-infra/prow/interrupts       30.039s
FAIL
```

/kind failing-test

**Comment by stevekuznetsov** [comment]
I think the stack trace posted is not representative of failures I'd expect to see in CI - the channel that is blocked on sending does not have a high capacity, but also we never run in parallel (on purpose) in CI. Let me look at [the stack](https://storage.googleapis.com/k8s-triage/index.html?date=2023-01-17&pr=1&test=TestInterrupts#4a204bb7b8310801efa4) in the triage dashboard.

**Comment by stevekuznetsov** [comment]
Yikes, I forgot how involved that code was. This comment on a function called in `init()` is suspicious:

```
// handleInterrupt turns an interrupt into a broadcast for our condition.
// This must be called _first_ before any work is registered with the
// manager, or there will be a deadlock.
```

It's called in a child go-routine from `init()` but we can't(?) wait until it starts to interrogate the channel for signals and this might be the cause of the deadlock. FWIW this code has not been touched in ~4y without any issues in "real life" so even if this issue in CI is theoretically possible it may not be worth a lot of effort to look into.

**Comment by aojea** [comment]
> I think the stack trace posted is not representative of failures I'd expect to see in CI - the channel that is blocked on sending does not have a high capacity, but also we never run in parallel (on purpose) in CI

`go test -timeout 30s -run ^TestInterrupts$ k8s.io/test-infra/prow/interrupts -count 10` runs in serial AFAIK

**Comment by aojea** [comment]
the first onen in https://storage.googleapis.com/k8s-triage/index.html?date=2023-01-17&pr=1&test=TestInterrupts

is not stuck waiting?
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-test-all/1610581817495130112

**Comment by stevekuznetsov** [comment]
Not sure what you mean - both of those are stuck waiting, not stuck sending like the one you posted. In any case, I don't really know that splitting this hair is very important. My analysis in https://github.com/kubernetes/test-infra/issues/29104#issuecomment-1479532263 applies to either situation.
