### ISSUE TITLE
Failed to append to gs://kubernetes-jenkins/pr-logs/.../pull-kubernetes-unit/jobResultsCache.json#0

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#4597]
Seeing PR unit failures with "out of space" messages like "Failed to append to gs://kubernetes-jenkins/pr-logs/pull/52603/pull-kubernetes-unit/jobResultsCache.json#0"

https://github.com/kubernetes/kubernetes/pull/52602
https://github.com/kubernetes/kubernetes/pull/52603

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52603/pull-kubernetes-unit/53802/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52602/pull-kubernetes-unit/53801/

```
W0917 01:01:37.699] Failed to append to gs://kubernetes-jenkins/pr-logs/pull/52603/pull-kubernetes-unit/jobResultsCache.json#0
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
... skipping 147 lines ...
  File "/usr/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
```

is this a known issue, or is it possible something in the PR itself could have caused this?

**Comment by BenTheElder** [comment]
I don't think this is a bootstrap bug, `pull-kubernetes-unit` is a Jenkins job, I'm guessing the worker ran out of disk?
/cc @krzyzacy

**Comment by liggitt** [comment]
seeing similar issues in other jobs

https://k8s-gubernator.appspot.com/pr/52604
https://prow.k8s.io/log?job=pull-kubernetes-e2e-gce-etcd3&id=54727

```
Logged from file bootstrap.py, line 67
I0917 03:44:11.547] process 3883 exited with code 0 after 0.0m
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
Logged from file bootstrap.py, line 143
I0917 03:44:11.548] Call:  gsutil -q cp -Z /var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/build-log.txt gs://kubernetes-jenkins/pr-logs/pull/52604/pull-kubernetes-e2e-gce-etcd3/54727/build-log.txt
W0917 03:44:12.205] Process SyncManager-1:
W0917 03:44:12.205] Traceback (most recent call last):
W0917 03:44:12.205]   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
W0917 03:44:12.205]     self.run()
W0917 03:44:12.205]   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
W0917 03:44:12.205]     self._target(*self._args, **self._kwargs)
W0917 03:44:12.205]   File "/usr/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
W0917 03:44:12.206]     server = cls._Server(registry, address, authkey, serializer)
W0917 03:44:12.206]   File "/usr/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
W0917 03:44:12.206]     self.listener = Listener(address=address, backlog=16)
W0917 03:44:12.206]   File "/usr/lib/python2.7/multiprocessing/connection.py", line 127, in __init__
W0917 03:44:12.206]     address = address or arbitrary_address(family)
W0917 03:44:12.206]   File "/usr/lib/python2.7/multiprocessing/connection.py", line 90, in arbitrary_address
W0917 03:44:12.206]     return tempfile.mktemp(prefix='listener-', dir=get_temp_dir())
W0917 03:44:12.206]   File "/usr/lib/python2.7/multiprocessing/util.py", line 139, in get_temp_dir
W0917 03:44:12.207]     tempdir = tempfile.mkdtemp(prefix='pymp-')
W0917 03:44:12.207]   File "/usr/lib/python2.7/tempfile.py", line 331, in mkdtemp
W0917 03:44:12.207]     dir = gettempdir()
W0917 03:44:12.207]   File "/usr/lib/python2.7/tempfile.py", line 275, in gettempdir
W0917 03:44:12.207]     tempdir = _get_default_tempdir()
W0917 03:44:12.207]   File "/usr/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
W0917 03:44:12.207]     ("No usable temporary directory found in %s" % dirlist))
W0917 03:44:12.208] IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/go/src/k8s.io/kubernetes']
W0917 03:44:12.292] Traceback (most recent call last):
W0917 03:44:12.292]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
W0917 03:44:12.292]     gsutil.RunMain()
W0917 03:44:12.292]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil.py", line 114, in RunMain
W0917 03:44:12.292]     sys.exit(gslib.__main__.main())
W0917 03:44:12.292]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 383, in main
W0917 03:44:12.292]     perf_trace_token=perf_trace_token)
W0917 03:44:12.292]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 577, in _RunNamedCommandAndHandleExceptions
W0917 03:44:12.292]     collect_analytics=True)
W0917 03:44:12.293]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 317, in RunNamedCommand
W0917 03:44:12.293]     return_code = command_inst.RunCommand()
W0917 03:44:12.293]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 1139, in RunCommand
W0917 03:44:12.293]     seek_ahead_iterator=seek_ahead_iterator)
W0917 03:44:12.293]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1368, in Apply
W0917 03:44:12.293]     arg_checker, should_return_results, fail_on_error)
W0917 03:44:12.293]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1439, in _SequentialApply
W0917 03:44:12.293]     worker_thread.PerformTask(task, self)
W0917 03:44:12.293]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command.py", line 2100, in PerformTask
W0917 03:44:12.293]     results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
W0917 03:44:12.294]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 753, in _CopyFuncWrapper
W0917 03:44:12.294]     preserve_posix=cls.preserve_posix_attrs)
W0917 03:44:12.294]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 947, in CopyFunc
W0917 03:44:12.294]     preserve_posix=preserve_posix))
W0917 03:44:12.294]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 3304, in PerformCopy
W0917 03:44:12.294]     allow_splitting=allow_splitting)
W0917 03:44:12.294]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 1744, in _UploadFileToObject
W0917 03:44:12.295]     src_url, src_obj_filestream, src_obj_size, logger)
W0917 03:44:12.295]   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 1669, in _CompressFileForUpload
W0917 03:44:12.295]     (gzip_fh, gzip_path) = tempfile.mkstemp()
W0917 03:44:12.295]   File "/usr/lib/python2.7/tempfile.py", line 307, in mkstemp
W0917 03:44:12.295]     dir = gettempdir()
W0917 03:44:12.295]   File "/usr/lib/python2.7/tempfile.py", line 275, in gettempdir
W0917 03:44:12.295]     tempdir = _get_default_tempdir()
W0917 03:44:12.295]   File "/usr/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
W0917 03:44:12.295]     ("No usable temporary directory found in %s" % dirlist))
W0917 03:44:12.295] IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/go/src/k8s.io/kubernetes']
E0917 03:44:12.373] Command failed
I0917 03:44:12.373] process 3902 exited with code 1 after 0.0m
```

**Comment by krzyzacy** [comment]
/close
this is due to some busted Jenkins agent and is stale now
