### ISSUE TITLE
"bazel build //..." fails due to `key "@io_bazel_rules_go//go:toolchain" not found in dictionary.`

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#5213]
Failure info:
```
~/go/src/k8s.io/test-infra$ bazel build //...
.............................
ERROR: /home/cloud/go/src/k8s.io/test-infra/mungegithub/sharedmux/BUILD:3:1: in go_library rule //mungegithub/sharedmux:go_default_library: 
Traceback (most recent call last):
	File "/home/cloud/go/src/k8s.io/test-infra/mungegithub/sharedmux/BUILD", line 3
		go_library(name = 'go_default_library')
	File "/home/cloud/.cache/bazel/_bazel_cloud/205787daa15053ebf44ed98597131a86/external/io_bazel_rules_go/go/private/rules/library.bzl", line 33, in _go_library_impl
		ctx.toolchains["@io_bazel_rules_go//go:toolchain"]
key "@io_bazel_rules_go//go:toolchain" not found in dictionary.
ERROR: Analysis of target '//mungegithub:go_default_library' failed; build aborted.
INFO: Elapsed time: 18.835s
```

Maybe I miss something in config (if any) ?

**Comment by BenTheElder** [comment]
Hmm, can you provide some more information like what `bazel version`, OS, test-infra commit?
/area bazel

**Comment by BenTheElder** [comment]
I'm actually running into another error:

```shell
ERROR: /private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/external/org_dropbox_rules_node/npm/chai/BUILD:7:1: installing node modules from external/org_dropbox_rules_node/npm/chai/npm-shrinkwrap.json failed (Exit 1).
/private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/bazel-sandbox/8086139377775195964/execroot/__main__/bazel-out/host/bin/external/org_dropbox_rules_node/node/tools/npm/install.runfiles/nodejs/bin/node: /private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/bazel-sandbox/8086139377775195964/execroot/__main__/bazel-out/host/bin/external/org_dropbox_rules_node/node/tools/npm/install.runfiles/nodejs/bin/node: cannot execute binary file
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/bazel-sandbox/8086139377775195964/execroot/__main__/bazel-out/host/bin/external/org_dropbox_rules_node/node/tools/npm/install.runfiles/__main__/../org_dropbox_rules_node/node/tools/npm/install.py", line 49, in <module>
    main()
  File "/private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/bazel-sandbox/8086139377775195964/execroot/__main__/bazel-out/host/bin/external/org_dropbox_rules_node/node/tools/npm/install.runfiles/__main__/../org_dropbox_rules_node/node/tools/npm/install.py", line 45, in main
    npm_install(args.shrinkwrap, args.output)
  File "/private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/bazel-sandbox/8086139377775195964/execroot/__main__/bazel-out/host/bin/external/org_dropbox_rules_node/node/tools/npm/install.runfiles/__main__/../org_dropbox_rules_node/node/tools/npm/install.py", line 27, in npm_install
    run_npm(['install'], env=env, cwd=output)
  File "/private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/bazel-sandbox/8086139377775195964/execroot/__main__/bazel-out/host/bin/external/org_dropbox_rules_node/node/tools/npm/install.runfiles/org_dropbox_rules_node/node/tools/npm/utils.py", line 93, in run_npm
    full_cmd, env=full_env, cwd=cwd, stderr=subprocess.STDOUT
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_bentheelder/4c072a8c986e7dd2b494f380f92d80d4/bazel-sandbox/8086139377775195964/execroot/__main__/bazel-out/host/bin/external/org_dropbox_rules_node/node/tools/npm/install.runfiles/nodejs/bin/npm', 'install']' returned non-zero exit status 126
```

cc @ixdy 
I will definitely investigate these further tomorrow (it's late here :smile: ), but in the meantime maybe try a `bazel clean --expunge`?

**Comment by xiangpengzhao** [comment]
Thanks @BenTheElder !

bazel version

```
Build label: 0.5.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 28 08:34:59 2017 (1501230899)
Build timestamp: 1501230899
Build timestamp as int: 1501230899
```

 uname -a

```
Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

git log

```
commit ac0e70702b56760f84642e25ab73354620e0a0a4
Merge: 36ebdee 53eccd6
Author: k8s-ci-robot <k8s-ci-robot@users.noreply.github.com>
Date:   Thu Oct 26 23:21:36 2017 -0700

    Merge pull request #4993 from ScorpioCPH/add-gopath-check
    
    Add GOPATH check
```

**Comment by xiangpengzhao** [comment]
I tried bazel clean but then the bazel build still failed.

**Comment by ixdy** [comment]
@xiangpengzhao ah, I think your version of bazel is too old for the version of `rules_go` we're using - can you update to 0.6.1 or 0.7.0?

@BenTheElder your issue looks like a cross-platform issue - note this error message: `.../external/org_dropbox_rules_node/node/tools/npm/install.runfiles/nodejs/bin/node: cannot execute binary file`

**Comment by xiangpengzhao** [comment]
@ixdy bazel 0.7.0 works. Thanks!

**Comment by BenTheElder** [comment]
Yes @ixdy but that was ssh'd to my workstation :/

**Comment by BenTheElder** [comment]
I think maybe on 0.7 the node rules don't install properly. I'll investigate.

**Comment by BenTheElder** [comment]
Well I can't reproduce now, but maybe we should document the bazel version used by test-infra somehwere @ixdy? I think the current minimum supported for k/t-i at least is `0.6.0`

**Comment by ixdy** [comment]
We're using https://github.com/kubernetes/repo-infra/blob/ae4e9a3906ace4ba657b7a09242610c6266e832c/defs/bazel_version.bzl#L19 on k/k; maybe we should use it on k/t-i, too.

**Comment by BenTheElder** [comment]
> We're using https://github.com/kubernetes/repo-infra/blob/ae4e9a3906ace4ba657b7a09242610c6266e832c/defs/bazel_version.bzl#L19 on k/k; maybe we should use it on k/t-i, too.

SGTM, I like when our error b̶a̶r̶f̶ logs actually have a line telling you what's wrong and how to fix it :-)
