### ISSUE TITLE
SQ graph has not updated since 11/17

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#5612]
```
Render results to buffer...
Traceback (most recent call last):
  File "/graph.py", line 476, in <module>
    render_forever(*sys.argv[1:])  # pylint: disable=no-value-for-parameter
  File "/graph.py", line 451, in render_forever
    output(history.split('\n')[-60*24*DAYS:], results)  # Last 21 days
  File "/graph.py", line 240, in output
    *line.strip().split(' '))
  File "/graph.py", line 55, in parse_line
    '%Y-%m-%d %H:%M:%S.%f'),
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017-11-17 13:04:47' does not match format '%Y-%m-%d %H:%M:%S.%f'
```

**Comment by BenTheElder** [comment]
fixed in https://github.com/kubernetes/test-infra/pull/5613
