### ISSUE TITLE
Planter: cannot get docker credentials

### ISSUE THREAD

**Issue by ash2k** [kubernetes/test-infra#5736]
On macOS when running bazel inside of the planter image the following error happens for me:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mmazurskiy/.cache/bazel/_bazel_mmazurskiy/b34360f02dd290fea1de7cb4ffb49b60/external/puller/file/puller.par/__main__.py", line 93, in <module>
  File "/Users/mmazurskiy/.cache/bazel/_bazel_mmazurskiy/b34360f02dd290fea1de7cb4ffb49b60/external/puller/file/puller.par/__main__.py", line 80, in main
  File "/Users/mmazurskiy/.cache/bazel/_bazel_mmazurskiy/b34360f02dd290fea1de7cb4ffb49b60/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 324, in __enter__
  File "/Users/mmazurskiy/.cache/bazel/_bazel_mmazurskiy/b34360f02dd290fea1de7cb4ffb49b60/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 193, in __init__
  File "/Users/mmazurskiy/.cache/bazel/_bazel_mmazurskiy/b34360f02dd290fea1de7cb4ffb49b60/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 272, in _Refresh
  File "/Users/mmazurskiy/.cache/bazel/_bazel_mmazurskiy/b34360f02dd290fea1de7cb4ffb49b60/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 153, in Get
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
rules_docker `container_pull` tries to pull base layer to be used in container building later but it fails. The script (see stacktrace) tries to execute `docker-credential-osxkeychain` to get credentials from osx keychain but of course it cannot - it is running inside of the docker image and there is no such file.
This only happens if there is `~/.docker/config.json` file. So the solution to this is to mount an empty directory on top of `~/.docker` and then it works fine.

Instead of
```shell
VOLUMES="-v ${REPO}:${REPO} -v ${HOME}:${HOME} --tmpfs /tmp:exec,mode=777"
```
do
```shell
VOLUMES="-v ${REPO}:${REPO} -v ${HOME}:${HOME} --mount type=tmpfs,destination=${HOME}/.docker --tmpfs /tmp:exec,mode=777"
```

p.s. [docs](https://docs.docker.com/engine/admin/volumes/tmpfs/) recommend to use `--mount` instead of `--tmpfs` so I used this syntax.

**Comment by ash2k** [comment]
@BenTheElder

**Comment by BenTheElder** [comment]
I've been meaning to change this to only mount the bazel cache instead. xref #5607

**Comment by BenTheElder** [comment]
> p.s. docs recommend to use --mount instead of --tmpfs so I used this syntax.

They do, but they also are light on mentioning that things like `:exec`, `:z`, `:Z` aren't supported for `--mount`. I'm going to leave the existing tmpfs flag as is since they don't seem to have a solution for this documented or planned anywhere.
