### ISSUE TITLE
Dead executors on Jenkins when we re-add jobs.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#601]
When we add jobs back to Jenkins that we have previously deleted, there is a chance that this will show up in the logs:

```
Sep 16, 2016 10:38:16 AM jenkins.model.RunIdMigrator migrate
INFO: Migrating build records in /var/lib/jenkins/jobs/kubernetes-e2e-gce-gci-ci-release-1.4/builds
Sep 16, 2016 10:38:16 AM jenkins.model.RunIdMigrator doMigrate
WARNING: found unexpected dir lastUnsuccessfulBuild
```

Then, the `nextBuildNumber` file won't get migrated, and so runs from then on will try to use build number 1, 2, etc, but fail with

```
java.lang.IllegalStateException: cannot create a build with number 1 since that (or higher) is already in use among [169]
        at jenkins.model.lazy.AbstractLazyLoadRunMap.proposeNewNumber(AbstractLazyLoadRunMap.java:373)
        at hudson.model.RunMap.put(RunMap.java:191)
        at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:176)
        at hudson.model.AbstractProject.newBuild(AbstractProject.java:1018)
        at hudson.model.AbstractProject.createExecutable(AbstractProject.java:1209)
        at hudson.model.AbstractProject.createExecutable(AbstractProject.java:144)
        at hudson.model.Executor$1.call(Executor.java:364)
        at hudson.model.Executor$1.call(Executor.java:346)
        at hudson.model.Queue._withLock(Queue.java:1373)
        at hudson.model.Queue.withLock(Queue.java:1234)
        at hudson.model.Executor.run(Executor.java:346)
```

This will permanently kill the executor that happened to try to run it.

To fix this quickly we can manually set `nextBuildNumber` and restart the Jenkins master, which is terrible. Alternatively, we can also delete the offending jobs, delete their data folders, delete the `jenkins-jobs` docker container (to clear its cache), and then rerun `kubernetes-update-jenkins-jobs`. That's pretty gross but at least it doesn't stop the world.

I'm looking into longer-term solutions.

**Comment by spxtr** [comment]
Longer-term solution is to stop using Jenkins.

/close
