### ISSUE TITLE
gubernator: never show me a stacktrace

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#6092]
Right now the most frustrating part of working with Gubernator is that any tiny inconsistency in `started.json` or `finished.json` can trigger a stacktrace and make the whole page fail to load for whatever view is requested.

We should try to make it so that this _never_ happens. One bit of information being missing should resolve in a `<missing>` field in the UI or simply no field in the UI. I'd like opinions on the best way to do this -- I am unfamiliar with the webapp framework used for the app, so perhaps there is a way to do it in that layer? Or in the templating layer? Or, alternatively, we should just ingest the data from GCS, transform it into an internal data structure and stub out or default out fields so that the templating layer down can always assume it has data.

/cc @cjwagner @rmmh @fejta @kargakis

**Comment by rmmh** [comment]
This is for making external build logs show on Gubernator, right?

**Comment by stevekuznetsov** [comment]
This is for any view - issues today exist with logs that are over size, missing or malformed data in `started.json` and `finished.json` that would usually be displayed in the header or the overview table.

**Comment by rmmh** [comment]
Running out of memory is the most common error on gubernator, especially for large artifact directories like the cluster scale logs.

**Comment by stevekuznetsov** [comment]
I'm not sure what you are saying. There are about ten million ways a malformed `finished.json` file will ruin the rendering of a page. For instance, [here](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_image-registry/21/openshift/image-registry/unit/1) with the following file:

```json
{
    "timestamp": 1514568015,
    "passed": false,
    "result": null
}
```

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~openshift-gce-devel/v20171115-f8b685f.405547338360504394/view_base.py", line 56, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~openshift-gce-devel/v20171115-f8b685f.405547338360504394/view_build.py", line 252, in get
    testgrid_query=testgrid_query))
  File "/base/data/home/apps/s~openshift-gce-devel/v20171115-f8b685f.405547338360504394/view_base.py", line 69, in render
    self.response.write(template.render(context))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~openshift-gce-devel/v20171115-f8b685f.405547338360504394/templates/build.html", line 1, in top-level template code
    % extends 'base.html'
  File "/base/data/home/apps/s~openshift-gce-devel/v20171115-f8b685f.405547338360504394/templates/base.html", line 26, in top-level template code
    % block content
  File "/base/data/home/apps/s~openshift-gce-devel/v20171115-f8b685f.405547338360504394/templates/build.html", line 31, in block "content"
    <tr><td>Result<td class="build-{{result | slugify}}">{{result}}
  File "/base/data/home/apps/s~openshift-gce-devel/v20171115-f8b685f.405547338360504394/filters.py", line 66, in do_slugify
    inp = re.sub(r'[^\w\s-]+', '', inp)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

Obviously `null` in the field is wrong, but the end result -- no view related to that build can ever load -- is the worst-case scenario. We should be much more tolerant of this. Just because the field is wrong doesn't mean you cannot show me if it passed or not (why is this separate from the `result` field again?), how long it took, the jUnit output, the builg log...

**Comment by stevekuznetsov** [comment]
@cjwagner @rmmh @fejta @kargakis 

Any thoughts?

**Comment by kargakis** [comment]
If there are cases where malformed metadata* blow up the Gubernator view when we could serve artifacts / test logs, we should fix it. 👍 

* or really anything that would not block us from serving whatever we have from tests.

**Comment by stevekuznetsov** [comment]
Seen [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63450/pull-kubernetes-verify/89530/):

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_base.py", line 85, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_build.py", line 236, in get
    build_dir, self.app.config.get('recursive_artifacts', True))
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_base.py", line 132, in wrapped
    data = func(*args)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_build.py", line 183, in build_details
    parser.parse_xml(future.get_result(), path)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_build.py", line 82, in parse_xml
    self.handle_suite(testsuite, filename)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_build.py", line 46, in handle_suite
    self.handle_test(subelement, filename, name_prefix)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_build.py", line 60, in handle_test
    self.failed.append((name, time, param.text, filename, '\n'.join(out)))
TypeError: sequence item 0: expected string, NoneType found
```
