### ISSUE TITLE
gubernator internal error displaying pr page

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7782]
https://k8s-gubernator.appspot.com/pr/test-infra/5137 -> 

# Internal Server Error

The server has either erred or is incapable of performing the requested operation.

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_base.py", line 85, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/view_pr.py", line 114, in get
    max_builds, headings, rows = pull_request.builds_to_table(builds)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/pull_request.py", line 44, in builds_to_table
    version = commit(started)
  File "/base/data/home/apps/s~k8s-gubernator/v20180416-c9119a012.409068688861151241/pull_request.py", line 34, in commit
    return started['version'].split('+')[-1]
KeyError: 'version'
```

/area gubernator
/kind bug
/assign @rmmh

**Comment by stevekuznetsov** [comment]
See also #6092

**Comment by rmmh** [comment]
/close

Missing versions are now marked 'unknown' instead of crashing.
