### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by leeivan** [kubernetes/test-infra#8552]
**Command:**
`go run hack/e2e.go -- --extract=release/stable-1.9 --up`
**Full output and error:**
```
2018/07/03 03:30:49 e2e.go:79: Calling kubetest --verbose-commands=true --extract=release/stable-1.9 --up...
2018/07/03 03:30:49 process.go:153: Running: gsutil cat gs://kubernetes-release/release/stable-1.9.txt
No command was given.

Choose one of -b, -d, -e, or -r to do something.
Try `/usr/bin/gsutil --help' for more information.
2018/07/03 03:30:49 process.go:155: Step 'gsutil cat gs://kubernetes-release/release/stable-1.9.txt' finished in 66.862913ms
2018/07/03 03:30:49 util.go:41: curl https://get.k8s.io
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.glob..func2(0xc4200f4500, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/extract_k8s.go:282 +0x84e
main.setReleaseFromGcs(0x14ca976, 0x1a, 0x7ffc0b42b757, 0xa, 0x413000, 0x135ed40, 0xc420232620)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/extract_k8s.go:313 +0x26e
main.extractStrategy.Extract(0x7, 0x7ffc0b42b757, 0xa, 0x0, 0x0, 0x7ffc0b42b74f, 0x12, 0x0, 0x0, 0x0, ...)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/extract_k8s.go:447 +0x1156
main.extractStrategies.Extract(0xc42030f240, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5e76cbc9300, ...)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/extract_k8s.go:146 +0x333
main.acquireKubernetes.func2(0xbec6e76a6a03aa8d, 0xe19368)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/main.go:465 +0xfc
k8s.io/test-infra/kubetest/process.(*Control).XMLWrap(0xc42030f280, 0x1ebbb20, 0x14b4e9c, 0x7, 0xc4204d9910, 0xc420092a58, 0x14b73af)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/process/process.go:103 +0x7e
main.acquireKubernetes(0xc420092800, 0x1607280, 0xc4202f8c70)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/main.go:442 +0x156
main.complete(0xc420092800, 0x0, 0x0)
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/main.go:360 +0x2f5
main.main()
	/home/leeivan/gowork/src/k8s.io/test-infra/kubetest/main.go:300 +0x463
2018/07/03 03:30:51 e2e.go:81: err: exit status 2
exit status 1
```

**Comment by BenTheElder** [comment]
@krzyzacy we should prevent this panic...

That said Kubernetes 1.5 is very out of support. With 1.11 out 1.8 is
making its way out and 1.9+ will be supported. The community supports 3
minor versions + 1 under development.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

**Comment by leeivan** [comment]
@BenTheElder 
Yes, using 1.9 to run the command, occurred same error.

**Comment by BenTheElder** [comment]
hmm I can't reproduce this... what is your kubernetes checkout version for hack/e2e.go? and your `gcloud --version`?

**Comment by krzyzacy** [comment]
I suspect your gsutil is not in a working state? 
Can you run `gsutil cat gs://kubernetes-release/release/stable-1.5.txt` locally?

**Comment by leeivan** [comment]
@krzyzacy 
Yes, the gsutil did not installed correctly. I found the right way to [install gsutil](https://cloud.google.com/storage/docs/gsutil_install#deb). Thanks.

**Comment by BenTheElder** [comment]
Thanks for following up! Glad it's working 🙂
