### ISSUE TITLE
Queue health utility is crash looping.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#9017]
```
NAME                                       READY     STATUS             RESTARTS   AGE
queue-health-4229917861-m5jg2              1/2       CrashLoopBackOff   798        208d
```

The error is coming from the `grapher` container:
```
['/graph.py',
 'gs://kubernetes-test-history/sq/history.txt',
 'gs://kubernetes-test-history/k8s-queue-health.svg',
 '/creds/service-account.json']
Activating service account using: /creds/service-account.json
Activated service account credentials for: [queue-health@kubernetes-jenkins.iam.gserviceaccount.com]
Truncate render buffer
Cat latest results from gs://kubernetes-test-history/sq/history.txt...
Render results to buffer...
Traceback (most recent call last):
  File "/graph.py", line 485, in <module>
    render_forever(*sys.argv[1:])  # pylint: disable=no-value-for-parameter
  File "/graph.py", line 461, in render_forever
    render(results, compressed)
  File "/graph.py", line 427, in render
    plt.savefig(out_file, bbox_inches='tight', format='svg')
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 561, in savefig
    return fig.savefig(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1421, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 2167, in print_figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1978, in print_svg
    return svg.print_svg(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_svg.py", line 1157, in print_svg
    return self._print_svg(filename, svgwriter, fh_to_close, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_svg.py", line 1185, in _print_svg
    self.figure.draw(renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1034, in draw
    func(*args)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2086, in draw
    a.draw(renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 1091, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 945, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 889, in iter_ticks
    majorLocs = self.major.locator()
  File "/usr/lib/pymodules/python2.7/matplotlib/dates.py", line 802, in __call__
    self.refresh()
  File "/usr/lib/pymodules/python2.7/matplotlib/dates.py", line 820, in refresh
    self._locator = self.get_locator(dmin, dmax)
  File "/usr/lib/pymodules/python2.7/matplotlib/dates.py", line 896, in get_locator
    raise ValueError('No sensible date limit could be found in the '
ValueError: No sensible date limit could be found in the AutoDateLocator.
```

/kind bug
/area mungegithub
/assign @fejta

**Comment by BenTheElder** [comment]
> ValueError: No sensible date limit could be found in the AutoDateLocator.

:laughing: this is fine

**Comment by spiffxp** [comment]
/close
welp, this doesn't make much sense now that mungegithub is gone
```
$ gcloud container clusters get-credentials "mungegithub" --project="k8s-mungegithub" --zone="us-central1-b"
$ k get pods | grep queue-health
queue-health-4229917861-m5jg2            2/2       Running   3729       281d
$ k get deploy | queue-health
queue-health           1         1         1            1           1y
$ k delete deploy queue-health
deployment.extensions "queue-health" deleted
```
